# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("credit_earned", "Credit Earned"),
                            ("credit_spent", "Credit Spent"),
                            ("credit_adjustment", "Manual Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.IntegerField(help_text="Positive=earned, negative=spent")),
                ("balance_after", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_creditled",
                "get_latest_by": "created_at",
            },
        ),
    ]
