# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resource_requests", "0001_initial"),
        ("analytics", "0002_initial"),
        ("hospitals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditledger",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_ledger_entries",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddField(
            model_name="creditledger",
            name="reference_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_entries",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddIndex(
            model_name="creditledger",
            index=models.Index(fields=["hospital", "-created_at"], name="analytics_c_hospita_1eb6c5_idx"),
        ),
    ]
