# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                (
                    "hospital_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("teaching", "Teaching"),
                            ("specialty", "Specialty"),
                            ("clinic", "Clinic"),
                            ("rehabilitation", "Rehabilitation"),
                            ("psychiatric", "Psychiatric"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, db_index=True, max_length=100)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                ("country", models.CharField(blank=True, db_index=True, max_length=100)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                (
                    "verified_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("suspended", "Suspended"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hospital",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HospitalAPIConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[("api", "API"), ("manual", "Manual"), ("csv_upload", "CSV Upload")], max_length=20
                    ),
                ),
                ("api_endpoint", models.CharField(blank=True, max_length=500)),
                (
                    "http_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST"), ("PUT", "PUT")], default="GET", max_length=10
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth"),
                            ("api_key", "API Key"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("encrypted_token", models.TextField(blank=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("sync_frequency", models.PositiveIntegerField(default=3600, help_text="Sync interval in seconds")),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hospital_api_config",
            },
        ),
        migrations.CreateModel(
            name="HospitalCapacity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("bed_total", models.PositiveIntegerField(default=0)),
                ("bed_available", models.PositiveIntegerField(default=0)),
                ("icu_total", models.PositiveIntegerField(default=0)),
                ("icu_available", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Hospital Capacities",
                "db_table": "hospital_capacity",
            },
        ),
        migrations.CreateModel(
            name="HospitalPartnership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("relationship_type", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended"), ("blocked", "Blocked")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships_as_a",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "hospital_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnerships_as_b",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "hospital_partnership",
            },
        ),
    ]
