# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resources", "0001_initial"),
        ("hospitals", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalpartnership",
            name="initiated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_partnerships",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="hospitalcapacity",
            name="hospital",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="capacity", to="hospitals.hospital"
            ),
        ),
        migrations.AddField(
            model_name="hospitalapiconfig",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="api_configs", to="hospitals.hospital"
            ),
        ),
        migrations.AddField(
            model_name="hospitalapiconfig",
            name="resource_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="api_configs", to="resources.resourcetype"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hospitalpartnership",
            unique_together={("hospital_a", "hospital_b")},
        ),
    ]
