# Generated by Django 4.2.16 on 2026-03-09 13:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        ("hospitals", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalRegistrationRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "hospital_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("teaching", "Teaching"),
                            ("specialty", "Specialty"),
                            ("clinic", "Clinic"),
                            ("rehabilitation", "Rehabilitation"),
                            ("psychiatric", "Psychiatric"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("active", "Active"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("api_base_url", models.CharField(blank=True, max_length=500)),
                (
                    "api_auth_type",
                    models.CharField(
                        choices=[
                            ("bearer", "Bearer Token"),
                            ("basic", "Basic Auth"),
                            ("api_key", "API Key"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("api_key", models.TextField(blank=True)),
                ("api_username", models.CharField(blank=True, max_length=200)),
                ("api_password", models.TextField(blank=True)),
                ("last_sync_time", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_registrations",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "hospital_registration_request",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(fields=["status"], name="hospital_re_status_000f80_idx"),
                    models.Index(fields=["registration_number"], name="hospital_re_registr_7ddb67_idx"),
                    models.Index(fields=["email"], name="hospital_re_email_cc1e40_idx"),
                    models.Index(fields=["submitted_at"], name="hospital_re_submitt_1a744b_idx"),
                ],
            },
        ),
    ]
