# Generated by Django 4.2.16 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0003_hospital_registration_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospitalregistrationrequest",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="hospitalregistrationrequest",
            name="registration_number",
            field=models.CharField(max_length=100),
        ),
    ]
