# Generated by Django 4.2.16 on 2026-03-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0004_alter_registration_request_non_unique_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalregistrationrequest",
            name="admin_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="hospitalregistrationrequest",
            name="admin_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="hospitalregistrationrequest",
            index=models.Index(fields=["admin_email"], name="hospital_re_admin_e_33b970_idx"),
        ),
    ]
