# Generated by Django 4.2.16 on 2026-03-14 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        ("hospitals", "0005_hospitalregistrationrequest_admin_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="verified_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("suspended", "Suspended"),
                    ("offboarded", "Offboarded"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HospitalOffboardingRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offboarding_requests",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_offboarding_records",
                        to="staff.staff",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_offboarding_records",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "hospital_offboarding_request",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(fields=["status"], name="hospital_of_status_fa8eee_idx"),
                    models.Index(fields=["hospital", "status"], name="hospital_of_hospita_f8be4a_idx"),
                    models.Index(fields=["requested_at"], name="hospital_of_request_ebb038_idx"),
                ],
            },
        ),
    ]
