# Generated by Django 4.2.16 on 2026-03-15 07:29

from django.db import migrations, models


def backfill_registration_admin_fields(apps, schema_editor):
    Registration = apps.get_model("hospitals", "HospitalRegistrationRequest")

    for registration in Registration.objects.all().iterator():
        changed = False

        if not registration.admin_name:
            registration.admin_name = registration.contact_name or registration.name
            changed = True

        if not registration.admin_email:
            registration.admin_email = registration.contact_email or registration.email
            changed = True

        if changed:
            registration.save(update_fields=["admin_name", "admin_email", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0007_hospital_contact_email_hospital_contact_name_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=backfill_registration_admin_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="hospitalregistrationrequest",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="hospitalregistrationrequest",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="hospitalregistrationrequest",
            name="contact_phone",
        ),
        migrations.AlterField(
            model_name="hospitalregistrationrequest",
            name="admin_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="hospitalregistrationrequest",
            name="admin_name",
            field=models.CharField(max_length=255),
        ),
    ]
