# Generated by Django 4.2.16 on 2026-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0009_hospital_facility_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="inventory_last_sync_source",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="hospital",
            name="inventory_source_type",
            field=models.CharField(
                choices=[("API", "API"), ("DASHBOARD", "Dashboard"), ("CSV", "CSV"), ("HYBRID", "Hybrid")],
                db_index=True,
                default="API",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="needs_inventory_dashboard",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hospitalregistrationrequest",
            name="inventory_last_sync_source",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="hospitalregistrationrequest",
            name="inventory_source_type",
            field=models.CharField(
                choices=[("API", "API"), ("DASHBOARD", "Dashboard"), ("CSV", "CSV"), ("HYBRID", "Hybrid")],
                db_index=True,
                default="API",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hospitalregistrationrequest",
            name="needs_inventory_dashboard",
            field=models.BooleanField(default=False),
        ),
    ]
