# Generated by Django 4.2.16 on 2026-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0011_hospitalregistrationrequest_api_check_results_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="advanced_integration_eligible",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="hospital",
            name="schema_contract_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="schema_contract_failed_apis",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hospital",
            name="schema_contract_status",
            field=models.CharField(
                choices=[("unchecked", "Unchecked"), ("passed", "Passed"), ("failed", "Failed")],
                db_index=True,
                default="unchecked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hospitalregistrationrequest",
            name="schema_contract_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospitalregistrationrequest",
            name="schema_contract_failed_apis",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="hospitalregistrationrequest",
            name="schema_contract_status",
            field=models.CharField(
                choices=[("unchecked", "Unchecked"), ("passed", "Passed"), ("failed", "Failed")],
                db_index=True,
                default="unchecked",
                max_length=20,
            ),
        ),
    ]
