# Generated by Django 4.2.16 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0012_hospital_advanced_integration_eligible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalupdaterequest",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="hospitalupdaterequest",
            name="review_comment",
            field=models.TextField(blank=True),
        ),
    ]
