-- =====================================================
-- HOSPITAL 5: ACADEMIC MEDICAL CENTER - Oracle Schema
-- Academic/Research terminology
-- =====================================================

-- =====================================================
-- RESEARCH_DIVISIONS (Departments)
-- =====================================================

CREATE TABLE research_divisions (
    division_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_code VARCHAR2(20) UNIQUE NOT NULL,
    division_name VARCHAR2(255) NOT NULL,
    research_focus VARCHAR2(20) CHECK (research_focus IN ('Clinical', 'Experimental', 'Educational', 'Administrative')),
    building_location VARCHAR2(100),
    floor_level NUMBER,
    annual_budget NUMBER(15,2),
    bed_capacity NUMBER DEFAULT 0,
    director_id NUMBER, -- References research_faculty
    established_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- RESEARCH_FACULTY (Staff)
-- =====================================================

CREATE TABLE research_faculty (
    faculty_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id NUMBER,
    faculty_number VARCHAR2(50) UNIQUE NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    academic_title VARCHAR2(255) NOT NULL,
    employment_type VARCHAR2(20) CHECK (employment_type IN ('Tenured', 'Non-Tenured', 'Adjunct', 'Visiting')),
    specialty_area VARCHAR2(255),
    license_credentials VARCHAR2(100) UNIQUE,
    research_level VARCHAR2(50),
    contact_phone VARCHAR2(20),
    institutional_email VARCHAR2(255) UNIQUE NOT NULL,
    appointment_date DATE,
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_faculty_division FOREIGN KEY (division_id) 
        REFERENCES research_divisions(division_id) ON DELETE SET NULL
);

-- Add foreign key constraint for division director
ALTER TABLE research_divisions ADD CONSTRAINT fk_division_director 
    FOREIGN KEY (director_id) REFERENCES research_faculty(faculty_id) ON DELETE SET NULL;

-- =====================================================
-- RESEARCH_SUBJECTS (Patients)
-- =====================================================

CREATE TABLE research_subjects (
    subject_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_number VARCHAR2(50) UNIQUE NOT NULL,
    full_name VARCHAR2(255) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR2(10) CHECK (gender IN ('Male', 'Female', 'Other')),
    blood_group VARCHAR2(5) CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    primary_phone VARCHAR2(20),
    email_contact VARCHAR2(255),
    residential_address CLOB,
    city VARCHAR2(100),
    state_province VARCHAR2(50),
    postal_code VARCHAR2(20),
    emergency_contact VARCHAR2(255),
    emergency_phone VARCHAR2(20),
    insurance_carrier VARCHAR2(255),
    policy_identifier VARCHAR2(100),
    known_allergies CLOB,
    research_notes CLOB,
    consent_status VARCHAR2(20) DEFAULT 'Pending' CHECK (consent_status IN ('Pending', 'Consented', 'Withdrawn')),
    enrollment_date DATE DEFAULT SYSDATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- THERAPEUTIC_COMPOUNDS (Medications)
-- =====================================================

CREATE TABLE therapeutic_compounds (
    compound_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compound_name VARCHAR2(255) NOT NULL,
    generic_identifier VARCHAR2(255),
    commercial_name VARCHAR2(255),
    concentration VARCHAR2(100),
    formulation VARCHAR2(100),
    administration_route VARCHAR2(100),
    pharmacological_class VARCHAR2(255),
    manufacturer_name VARCHAR2(255),
    regulatory_number VARCHAR2(50) UNIQUE,
    controlled_status NUMBER(1) DEFAULT 0,
    prescription_only NUMBER(1) DEFAULT 1,
    research_grade NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- COMPOUND_INVENTORY (Medication Inventory)
-- =====================================================

CREATE TABLE compound_inventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compound_id NUMBER NOT NULL,
    lot_number VARCHAR2(100),
    available_quantity NUMBER NOT NULL DEFAULT 0,
    cost_per_unit NUMBER(10,2),
    expiry_date DATE,
    production_date DATE,
    supplier_name VARCHAR2(255),
    minimum_stock NUMBER DEFAULT 10,
    maximum_stock NUMBER,
    storage_conditions VARCHAR2(255),
    last_audit_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_compound_lot UNIQUE (compound_id, lot_number),
    CONSTRAINT fk_inventory_compound FOREIGN KEY (compound_id) 
        REFERENCES therapeutic_compounds(compound_id) ON DELETE CASCADE
);

-- =====================================================
-- RESEARCH_EQUIPMENT (Medical Equipment)
-- =====================================================

CREATE TABLE research_equipment (
    equipment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division_id NUMBER,
    equipment_name VARCHAR2(255) NOT NULL,
    equipment_category VARCHAR2(50) CHECK (equipment_category IN ('Diagnostic', 'Analytical', 'Monitoring', 'Laboratory', 'Imaging', 'Surgical')),
    model_number VARCHAR2(255),
    manufacturer_name VARCHAR2(255),
    serial_identifier VARCHAR2(100) UNIQUE,
    acquisition_date DATE,
    acquisition_cost NUMBER(12,2),
    warranty_end_date DATE,
    last_calibration DATE,
    next_calibration DATE,
    operational_status VARCHAR2(20) DEFAULT 'Operational' 
        CHECK (operational_status IN ('Operational', 'In Use', 'Maintenance', 'Calibration', 'Decommissioned')),
    physical_location VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_equipment_division FOREIGN KEY (division_id) 
        REFERENCES research_divisions(division_id) ON DELETE SET NULL
);

-- =====================================================
-- STUDY_SESSIONS (Appointments)
-- =====================================================

CREATE TABLE study_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id NUMBER NOT NULL,
    faculty_id NUMBER NOT NULL,
    division_id NUMBER,
    session_datetime TIMESTAMP NOT NULL,
    duration_minutes NUMBER DEFAULT 60,
    session_type VARCHAR2(50) CHECK (session_type IN ('Screening', 'Baseline', 'Follow-up', 'Intervention', 'Final')),
    study_protocol VARCHAR2(255),
    session_status VARCHAR2(20) DEFAULT 'Scheduled' 
        CHECK (session_status IN ('Scheduled', 'Confirmed', 'In Progress', 'Completed', 'Cancelled', 'No Show')),
    research_notes CLOB,
    compensation_amount NUMBER(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_session_subject FOREIGN KEY (subject_id) 
        REFERENCES research_subjects(subject_id) ON DELETE CASCADE,
    CONSTRAINT fk_session_faculty FOREIGN KEY (faculty_id) 
        REFERENCES research_faculty(faculty_id) ON DELETE CASCADE,
    CONSTRAINT fk_session_division FOREIGN KEY (division_id) 
        REFERENCES research_divisions(division_id) ON DELETE SET NULL
);

-- =====================================================
-- RESEARCH_DOCUMENTATION (Medical Records)
-- =====================================================

CREATE TABLE research_documentation (
    document_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id NUMBER NOT NULL,
    session_id NUMBER,
    faculty_id NUMBER,
    document_type VARCHAR2(50) CHECK (document_type IN ('Lab Report', 'Imaging Study', 'Research Note', 'Protocol Deviation', 'Adverse Event')),
    documentation_date DATE NOT NULL,
    document_title VARCHAR2(255) NOT NULL,
    document_content CLOB,
    research_findings CLOB,
    protocol_compliance VARCHAR2(20) DEFAULT 'Compliant' 
        CHECK (protocol_compliance IN ('Compliant', 'Minor Deviation', 'Major Deviation')),
    documented_by NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_subject FOREIGN KEY (subject_id) 
        REFERENCES research_subjects(subject_id) ON DELETE CASCADE,
    CONSTRAINT fk_doc_session FOREIGN KEY (session_id) 
        REFERENCES study_sessions(session_id) ON DELETE SET NULL,
    CONSTRAINT fk_doc_faculty FOREIGN KEY (faculty_id) 
        REFERENCES research_faculty(faculty_id) ON DELETE SET NULL,
    CONSTRAINT fk_doc_creator FOREIGN KEY (documented_by) 
        REFERENCES research_faculty(faculty_id)
);

-- =====================================================
-- COMPOUND_PROTOCOLS (Prescriptions)
-- =====================================================

CREATE TABLE compound_protocols (
    protocol_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id NUMBER NOT NULL,
    faculty_id NUMBER NOT NULL,
    compound_id NUMBER NOT NULL,
    session_id NUMBER,
    protocol_date DATE NOT NULL,
    dosage_amount VARCHAR2(255),
    administration_frequency VARCHAR2(100),
    treatment_duration NUMBER,
    quantity_dispensed NUMBER,
    refills_authorized NUMBER DEFAULT 0,
    refills_dispensed NUMBER DEFAULT 0,
    protocol_status VARCHAR2(20) DEFAULT 'Active' 
        CHECK (protocol_status IN ('Active', 'Completed', 'Discontinued', 'On Hold')),
    special_instructions CLOB,
    adverse_reactions CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_protocol_subject FOREIGN KEY (subject_id) 
        REFERENCES research_subjects(subject_id) ON DELETE CASCADE,
    CONSTRAINT fk_protocol_faculty FOREIGN KEY (faculty_id) 
        REFERENCES research_faculty(faculty_id) ON DELETE CASCADE,
    CONSTRAINT fk_protocol_compound FOREIGN KEY (compound_id) 
        REFERENCES therapeutic_compounds(compound_id) ON DELETE CASCADE,
    CONSTRAINT fk_protocol_session FOREIGN KEY (session_id) 
        REFERENCES study_sessions(session_id) ON DELETE SET NULL
);

-- =====================================================
-- SPECIMEN_BANK (Blood Bank - Research focused)
-- =====================================================

CREATE TABLE specimen_bank (
    specimen_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id NUMBER NOT NULL,
    specimen_type VARCHAR2(50) CHECK (specimen_type IN ('Blood', 'Plasma', 'Serum', 'Urine', 'Tissue', 'Saliva')),
    collection_date DATE NOT NULL,
    collection_time TIMESTAMP,
    volume_ml NUMBER(8,2),
    storage_temperature NUMBER(5,2),
    storage_location VARCHAR2(100),
    processing_status VARCHAR2(20) DEFAULT 'Collected' 
        CHECK (processing_status IN ('Collected', 'Processed', 'Stored', 'Analyzed', 'Depleted')),
    quality_grade VARCHAR2(20),
    research_protocol VARCHAR2(100),
    collected_by NUMBER,
    special_handling CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_specimen_subject FOREIGN KEY (subject_id) 
        REFERENCES research_subjects(subject_id) ON DELETE CASCADE,
    CONSTRAINT fk_specimen_collector FOREIGN KEY (collected_by) 
        REFERENCES research_faculty(faculty_id)
);

-- =====================================================
-- Create indexes for better performance
-- =====================================================

CREATE INDEX idx_faculty_division ON research_faculty(division_id);
CREATE INDEX idx_subject_enrollment ON research_subjects(enrollment_date);
CREATE INDEX idx_session_datetime ON study_sessions(session_datetime);
CREATE INDEX idx_session_subject ON study_sessions(subject_id);
CREATE INDEX idx_inventory_compound ON compound_inventory(compound_id);
CREATE INDEX idx_equipment_division ON research_equipment(division_id);
CREATE INDEX idx_doc_subject ON research_documentation(subject_id);
CREATE INDEX idx_protocol_subject ON compound_protocols(subject_id);
CREATE INDEX idx_specimen_subject ON specimen_bank(subject_id);

-- =====================================================
-- INSERT INITIAL RESEARCH DIVISIONS
-- =====================================================

INSERT INTO research_divisions (division_code, division_name, research_focus, building_location, floor_level, annual_budget, bed_capacity, established_date) VALUES
('RES-001', 'Clinical Research Division', 'Clinical', 'Research Tower A', 3, 3500000.00, 40, DATE '2008-01-15');

INSERT INTO research_divisions (division_code, division_name, research_focus, building_location, floor_level, annual_budget, bed_capacity, established_date) VALUES
('LAB-001', 'Laboratory Sciences', 'Experimental', 'Research Tower B', 2, 2800000.00, 0, DATE '2010-05-20');

INSERT INTO research_divisions (division_code, division_name, research_focus, building_location, floor_level, annual_budget, bed_capacity, established_date) VALUES
('EDU-001', 'Medical Education Department', 'Educational', 'Academic Center', 4, 1200000.00, 0, DATE '2005-09-01');

INSERT INTO research_divisions (division_code, division_name, research_focus, building_location, floor_level, annual_budget, bed_capacity, established_date) VALUES
('IMG-001', 'Advanced Imaging Research', 'Clinical', 'Diagnostic Center', 1, 4200000.00, 15, DATE '2012-03-10');

INSERT INTO research_divisions (division_code, division_name, research_focus, building_location, floor_level, annual_budget, bed_capacity, established_date) VALUES
('PHM-001', 'Pharmaceutical Research', 'Experimental', 'Research Tower C', 3, 3100000.00, 0, DATE '2009-07-22');

INSERT INTO research_divisions (division_code, division_name, research_focus, building_location, floor_level, annual_budget, bed_capacity, established_date) VALUES
('GEN-001', 'Genetics and Genomics', 'Experimental', 'Research Tower D', 5, 5200000.00, 20, DATE '2015-11-08');

INSERT INTO research_divisions (division_code, division_name, research_focus, building_location, floor_level, annual_budget, bed_capacity, established_date) VALUES
('ADM-001', 'Research Administration', 'Administrative', 'Administration Building', 2, 800000.00, 0, DATE '2005-01-01');

-- Commit the changes
COMMIT;