# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("message", models.TextField()),
                (
                    "scope",
                    models.CharField(
                        choices=[("all", "System-Wide"), ("hospitals", "Specific Hospitals")],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("urgent", "Urgent"), ("emergency", "Emergency")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_hospitals",
                    models.ManyToManyField(blank=True, related_name="targeted_broadcasts", to="hospitals.hospital"),
                ),
            ],
            options={
                "db_table": "notifications_broadcast",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("request_received", "Request Received"),
                            ("request_approved", "Request Approved"),
                            ("request_rejected", "Request Rejected"),
                            ("request_dispatched", "Request Dispatched"),
                            ("request_delivered", "Request Delivered"),
                            ("invitation_sent", "Invitation Sent"),
                            ("broadcast", "Broadcast"),
                            ("system", "System"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_notification",
                "indexes": [
                    models.Index(fields=["user", "is_read", "-created_at"], name="notificatio_user_id_f2ad08_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyBroadcastResponse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("can_provide", models.BooleanField(default=False)),
                ("quantity_available", models.PositiveIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="notifications.broadcastmessage",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_responses",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_emergencyresponse",
                "unique_together": {("broadcast", "hospital")},
            },
        ),
    ]
