# Generated by Django 4.2.16 on 2026-03-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastmessage",
            name="allow_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="broadcastmessage",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="broadcastmessage",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcasts_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="broadcastmessage",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("closed", "Closed")],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emergencybroadcastresponse",
            name="response_message",
            field=models.TextField(blank=True),
        ),
    ]
