# Generated by Django 4.2.16 on 2026-03-15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0008_remove_hospital_contact_email_and_more"),
        ("notifications", "0002_broadcast_response_controls"),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastRecipient",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notifications.broadcastmessage",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_recipients",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_broadcastrecipient",
                "indexes": [
                    models.Index(fields=["hospital", "is_read"], name="notificatio_hospita_31081d_idx"),
                    models.Index(fields=["broadcast", "hospital"], name="notificatio_broadca_60e9af_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("broadcast", "hospital"), name="uniq_broadcast_hospital_recipient"),
                ],
            },
        ),
    ]
