# Generated by Django 4.2.16 on 2026-04-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0003_broadcastrecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastmessage",
            name="location",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="BroadcastChangeVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.CharField(default="global", max_length=32, unique=True)),
                ("version", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notifications_broadcast_change_version",
            },
        ),
        migrations.CreateModel(
            name="BroadcastClientCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_seen_version", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_client_cursor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications_broadcast_client_cursor",
            },
        ),
    ]
