version: "3.9"

services:
  city-general:
    build: ./city-general
    ports:
      - "9001:8000"

  metro-medical:
    build: ./metro-medical
    ports:
      - "9002:8000"

  sunrise-health:
    build: ./sunrise-health
    ports:
      - "9003:8000"

  green-valley:
    build: ./green-valley
    ports:
      - "9004:8000"
