# Generated by Django 4.2.16 on 2026-03-15 07:45

from django.db import migrations, models
import django.db.models.deletion


def backfill_staff_email_and_role(apps, schema_editor):
    Staff = apps.get_model("staff", "Staff")
    Invitation = apps.get_model("staff", "Invitation")
    UserRole = apps.get_model("staff", "UserRole")
    UserAccount = apps.get_model("authentication", "UserAccount")

    for staff in Staff.objects.all().iterator():
        changed = False

        if not staff.email:
            account = UserAccount.objects.filter(staff_id=staff.id).only("email").first()
            if account and account.email:
                staff.email = account.email
                changed = True
            else:
                invitation = Invitation.objects.filter(staff_id=staff.id).only("email").first()
                if invitation and invitation.email:
                    staff.email = invitation.email
                    changed = True

        if not staff.role_id:
            account = UserAccount.objects.filter(staff_id=staff.id).only("id").first()
            if account:
                user_role = UserRole.objects.filter(user_id=account.id).order_by("assigned_at").first()
                if user_role:
                    staff.role_id = user_role.role_id
                    changed = True

            if not staff.role_id:
                invitation = Invitation.objects.filter(staff_id=staff.id).only("role_id").first()
                if invitation and invitation.role_id:
                    staff.role_id = invitation.role_id
                    changed = True

        if changed:
            staff.save(update_fields=["email", "role", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(blank=True, db_index=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="staff",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="staff.role",
            ),
        ),
        migrations.RunPython(
            code=backfill_staff_email_and_role,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
