# Generated by Django 4.2.16 on 2026-03-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_staff_email_staff_role"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staff",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employment_status", "active"), models.Q(("employee_id", ""), _negated=True)),
                fields=("hospital", "employee_id"),
                name="uniq_active_staff_employee_per_hospital",
            ),
        ),
    ]
