# Generated by Django 4.2.16 on 2026-04-03 00:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0003_alter_staff_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z][A-Z0-9_]*$",
                                "Use UPPER_SNAKE_CASE (e.g. CREATE_USER).",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "staff_permission",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="staff.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="staff.role",
                    ),
                ),
            ],
            options={
                "db_table": "staff_role_permission",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="staff.RolePermission",
                through_fields=("role", "permission"),
                to="staff.permission",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"),
                name="uniq_staff_role_permission",
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["is_active"], name="staff_permi_is_acti_008d29_idx"),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["role", "permission"], name="staff_role__role_id_d0d4e6_idx"),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["permission", "role"], name="staff_role__permiss_61a2ec_idx"),
        ),
    ]
