# Generated by Django 4.2.16 on 2026-04-03 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0012_hospital_advanced_integration_eligible_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0004_permission_rolepermission_and_role_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z][A-Z0-9_]*$", "Use UPPER_SNAKE_CASE (e.g. PHARMACY_MANAGER)."
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hospital_role",
            },
        ),
        migrations.CreateModel(
            name="HospitalRolePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hospital_role_permission",
            },
        ),
        migrations.CreateModel(
            name="PlatformRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z][A-Z0-9_]*$", "Use UPPER_SNAKE_CASE (e.g. PLATFORM_ADMIN)."
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "platform_role",
            },
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?:[A-Z][A-Z0-9_]*|[a-z][a-z0-9]*(?::[a-z][a-z0-9]*)?(?:\\.[a-z][a-z0-9]*)*)$",
                        "Use UPPER_SNAKE_CASE (legacy) or namespaced lowercase (e.g. platform:role.assign).",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="UserPlatformRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_platform_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="staff.platformrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_platform_role",
            },
        ),
        migrations.CreateModel(
            name="UserHospitalRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_user_hospital_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_hospital_roles",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "hospital_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="staff.hospitalrole",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_role_assignment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_hospital_role",
            },
        ),
        migrations.CreateModel(
            name="PlatformRolePermission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_platform_role_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_role_permissions",
                        to="staff.permission",
                    ),
                ),
                (
                    "platform_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="staff.platformrole",
                    ),
                ),
            ],
            options={
                "db_table": "platform_role_permission",
            },
        ),
        migrations.AddIndex(
            model_name="platformrole",
            index=models.Index(fields=["is_active"], name="platform_ro_is_acti_78e04b_idx"),
        ),
        migrations.AddField(
            model_name="hospitalrolepermission",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_hospital_role_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hospitalrolepermission",
            name="hospital_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="role_permissions", to="staff.hospitalrole"
            ),
        ),
        migrations.AddField(
            model_name="hospitalrolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hospital_role_permissions",
                to="staff.permission",
            ),
        ),
        migrations.AddField(
            model_name="hospitalrole",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="hospital_roles", to="hospitals.hospital"
            ),
        ),
        migrations.AddIndex(
            model_name="userplatformrole",
            index=models.Index(fields=["user", "platform_role"], name="user_platfo_user_id_209308_idx"),
        ),
        migrations.AddConstraint(
            model_name="userplatformrole",
            constraint=models.UniqueConstraint(fields=("user", "platform_role"), name="uniq_user_platform_role"),
        ),
        migrations.AddIndex(
            model_name="userhospitalrole",
            index=models.Index(fields=["hospital", "hospital_role"], name="user_hospit_hospita_4d4154_idx"),
        ),
        migrations.AddIndex(
            model_name="userhospitalrole",
            index=models.Index(fields=["user"], name="user_hospit_user_id_b1f0ff_idx"),
        ),
        migrations.AddIndex(
            model_name="platformrolepermission",
            index=models.Index(fields=["platform_role", "permission"], name="platform_ro_platfor_1e442f_idx"),
        ),
        migrations.AddIndex(
            model_name="platformrolepermission",
            index=models.Index(fields=["permission", "platform_role"], name="platform_ro_permiss_f3c6e1_idx"),
        ),
        migrations.AddConstraint(
            model_name="platformrolepermission",
            constraint=models.UniqueConstraint(
                fields=("platform_role", "permission"), name="uniq_platform_role_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalrolepermission",
            index=models.Index(fields=["hospital_role", "permission"], name="hospital_ro_hospita_be25d6_idx"),
        ),
        migrations.AddIndex(
            model_name="hospitalrolepermission",
            index=models.Index(fields=["permission", "hospital_role"], name="hospital_ro_permiss_13b741_idx"),
        ),
        migrations.AddConstraint(
            model_name="hospitalrolepermission",
            constraint=models.UniqueConstraint(
                fields=("hospital_role", "permission"), name="uniq_hospital_role_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitalrole",
            index=models.Index(fields=["hospital", "is_active"], name="hospital_ro_hospita_3a9a31_idx"),
        ),
        migrations.AddIndex(
            model_name="hospitalrole",
            index=models.Index(fields=["name"], name="hospital_ro_name_774979_idx"),
        ),
        migrations.AddConstraint(
            model_name="hospitalrole",
            constraint=models.UniqueConstraint(fields=("hospital", "name"), name="uniq_hospital_role_name"),
        ),
    ]
