# Generated by Django 4.2.16 on 2026-04-04 11:30

from django.db import migrations


PERMISSIONS = [
    # Platform and authorization meta
    {
        "code": "platform:role.view",
        "name": "View Platform Roles",
        "description": "View platform role definitions and role-permission mappings.",
    },
    {
        "code": "platform:role.manage",
        "name": "Manage Platform Roles",
        "description": "Create, update, and delete platform role definitions.",
    },
    {
        "code": "platform:role.assign",
        "name": "Assign Platform Roles",
        "description": "Assign and revoke platform roles for users.",
    },
    {
        "code": "platform:permission.view",
        "name": "View Permission Catalog",
        "description": "View the global permission catalog for RBAC operations.",
    },
    {
        "code": "platform:user.view",
        "name": "View Platform Users",
        "description": "View users across hospitals and inspect role mappings.",
    },
    {
        "code": "platform:user_role.view",
        "name": "View User Role Assignments",
        "description": "View platform and hospital role assignments for users.",
    },
    {
        "code": "platform:user_role.assign",
        "name": "Assign User Roles",
        "description": "Assign and revoke RBAC role assignments for users.",
    },
    {
        "code": "platform:hospital.view",
        "name": "View Hospitals",
        "description": "View hospital records across the platform.",
    },
    {
        "code": "platform:hospital.manage",
        "name": "Manage Hospitals",
        "description": "Perform platform-level hospital lifecycle operations.",
    },
    {
        "code": "platform:hospital.review",
        "name": "Review Hospital Requests",
        "description": "Review, approve, and reject hospital registration and lifecycle requests.",
    },
    {
        "code": "platform:audit.view",
        "name": "View Platform Audit Logs",
        "description": "View authorization and audit logs at platform scope.",
    },
    {
        "code": "auth:permission.effective.view",
        "name": "View Effective Permissions",
        "description": "Inspect a user\'s effective permission union across all scopes.",
    },

    # Hospital core administration
    {
        "code": "hospital:hospital.view",
        "name": "View Hospital Profile",
        "description": "View hospital profile and hospital-scoped configuration.",
    },
    {
        "code": "hospital:hospital.update",
        "name": "Update Hospital Profile",
        "description": "Update hospital profile fields and submit update workflows.",
    },
    {
        "code": "hospital:hospital.capacity.view",
        "name": "View Hospital Capacity",
        "description": "View hospital capacity configuration.",
    },
    {
        "code": "hospital:hospital.capacity.update",
        "name": "Update Hospital Capacity",
        "description": "Update hospital capacity configuration.",
    },
    {
        "code": "hospital:integration.view",
        "name": "View Hospital Integrations",
        "description": "View hospital integration API configuration.",
    },
    {
        "code": "hospital:integration.manage",
        "name": "Manage Hospital Integrations",
        "description": "Create, update, sync, and delete hospital integration API configuration.",
    },
    {
        "code": "hospital:offboarding.request",
        "name": "Request Hospital Offboarding",
        "description": "Submit hospital offboarding requests for administrative review.",
    },
    {
        "code": "hospital:staff.view",
        "name": "View Hospital Staff",
        "description": "View staff profiles for the hospital.",
    },
    {
        "code": "hospital:staff.manage",
        "name": "Manage Hospital Staff",
        "description": "Create and manage hospital staff records and invitations.",
    },
    {
        "code": "hospital:staff.supervise",
        "name": "Supervise Hospital Staff",
        "description": "Suspend staff, revoke invites, and perform supervisory staff operations.",
    },
    {
        "code": "hospital:invitation.view",
        "name": "View Invitations",
        "description": "View invitation records for hospital staff onboarding.",
    },
    {
        "code": "hospital:invitation.manage",
        "name": "Manage Invitations",
        "description": "Create and revoke invitation records for staff onboarding.",
    },
    {
        "code": "hospital:role.view",
        "name": "View Hospital Roles",
        "description": "View hospital-scoped role definitions and mappings.",
    },
    {
        "code": "hospital:role.manage",
        "name": "Manage Hospital Roles",
        "description": "Create and manage hospital-scoped role definitions.",
    },
    {
        "code": "hospital:user_role.view",
        "name": "View Hospital User Roles",
        "description": "View hospital role assignments for users.",
    },
    {
        "code": "hospital:user_role.assign",
        "name": "Assign Hospital Roles",
        "description": "Assign and revoke a user\'s hospital role.",
    },

    # Inventory and resource catalog
    {
        "code": "hospital:catalog.view",
        "name": "View Resource Catalog",
        "description": "View resource catalog entries for a hospital.",
    },
    {
        "code": "hospital:catalog.manage",
        "name": "Manage Resource Catalog",
        "description": "Create, update, and delete resource catalog entries.",
    },
    {
        "code": "hospital:inventory.view",
        "name": "View Hospital Inventory",
        "description": "View hospital inventory and catalog data.",
    },
    {
        "code": "hospital:inventory.edit",
        "name": "Edit Hospital Inventory",
        "description": "Edit hospital inventory quantities and item metadata.",
    },
    {
        "code": "hospital:inventory.manage",
        "name": "Manage Hospital Inventory",
        "description": "Manage hospital inventory lifecycle operations.",
    },
    {
        "code": "hospital:inventory.supervise",
        "name": "Supervise Hospital Inventory",
        "description": "Perform supervisory inventory controls and policy updates.",
    },
    {
        "code": "hospital:inventory.import",
        "name": "Import Inventory Data",
        "description": "Validate and commit inventory imports from CSV and integration pipelines.",
    },
    {
        "code": "hospital:resource_share.view",
        "name": "View Resource Shares",
        "description": "View resource sharing offers across hospitals.",
    },
    {
        "code": "hospital:resource_share.manage",
        "name": "Manage Resource Shares",
        "description": "Create and update resource sharing offers.",
    },
    {
        "code": "hospital:resource_share.supervise",
        "name": "Supervise Resource Shares",
        "description": "Close or force-update resource sharing offers.",
    },
    {
        "code": "hospital:resource_share.visibility.view",
        "name": "View Share Visibility",
        "description": "View inventory share visibility and offered quantities.",
    },
    {
        "code": "hospital:sales.view",
        "name": "View Sales Records",
        "description": "View operational sales resources and sale records.",
    },
    {
        "code": "hospital:sales.manage",
        "name": "Manage Sales Records",
        "description": "Create and manage operational sales records.",
    },
    {
        "code": "hospital:analytics.view",
        "name": "View Hospital Analytics",
        "description": "View analytics and credit ledger data for the hospital.",
    },

    # Request, payment, and transport workflow
    {
        "code": "hospital:request.view",
        "name": "View Hospital Requests",
        "description": "View hospital resource requests.",
    },
    {
        "code": "hospital:request.create",
        "name": "Create Hospital Requests",
        "description": "Create hospital resource requests.",
    },
    {
        "code": "hospital:request.approve",
        "name": "Approve Hospital Requests",
        "description": "Approve hospital resource requests.",
    },
    {
        "code": "hospital:request.supervise",
        "name": "Supervise Hospital Requests",
        "description": "Perform privileged request actions including cancellation and override transitions.",
    },
    {
        "code": "hospital:request.dispatch",
        "name": "Dispatch Requests",
        "description": "Dispatch approved resource requests for transport workflows.",
    },
    {
        "code": "hospital:request.reserve",
        "name": "Reserve Request Inventory",
        "description": "Reserve supplier inventory for approved requests.",
    },
    {
        "code": "hospital:request.transfer.confirm",
        "name": "Confirm Transfers",
        "description": "Confirm transfer completion and receiving quantities.",
    },
    {
        "code": "hospital:request.delivery.confirm",
        "name": "Confirm Deliveries",
        "description": "Confirm request deliveries via token-based handover workflows.",
    },
    {
        "code": "hospital:request.return.verify",
        "name": "Verify Request Returns",
        "description": "Verify request return flows and return tokens.",
    },
    {
        "code": "hospital:request.expire",
        "name": "Expire Requests",
        "description": "Run request expiration workflows for overdue requests.",
    },
    {
        "code": "hospital:payment.view",
        "name": "View Payment Transactions",
        "description": "View payment transaction history and states for hospital requests.",
    },
    {
        "code": "hospital:payment.initiate",
        "name": "Initiate Payments",
        "description": "Initiate payment transactions for payable requests.",
    },
    {
        "code": "hospital:payment.confirm",
        "name": "Confirm Payments",
        "description": "Confirm pending payment transactions.",
    },
    {
        "code": "hospital:payment.refund.initiate",
        "name": "Initiate Refunds",
        "description": "Initiate refunds for completed payment transactions.",
    },
    {
        "code": "hospital:payment.refund.confirm",
        "name": "Confirm Refunds",
        "description": "Confirm initiated refunds.",
    },
    {
        "code": "hospital:payment.report.view",
        "name": "View Payment Reports",
        "description": "Access payment reporting summaries for reconciliation and audits.",
    },
    {
        "code": "hospital:payment.reconcile.manage",
        "name": "Manage Payment Reconciliation",
        "description": "Run and manage payment reconciliation workflows.",
    },
    {
        "code": "hospital:transport.view",
        "name": "View Transport Operations",
        "description": "View shipment, dispatch, and transport tracking operations.",
    },
    {
        "code": "hospital:transport.create",
        "name": "Create Transport Operations",
        "description": "Create shipment and transport records.",
    },
    {
        "code": "hospital:transport.update",
        "name": "Update Transport Operations",
        "description": "Update shipment status and transport operation metadata.",
    },
    {
        "code": "hospital:transport.assign",
        "name": "Assign Transport Resources",
        "description": "Assign riders and related transport resources.",
    },
    {
        "code": "hospital:transport.track",
        "name": "Track Transport Operations",
        "description": "Add and view shipment tracking events.",
    },

    # Legacy communication codes retained for compatibility
    {
        "code": "hospital:communication.view",
        "name": "View Hospital Communications",
        "description": "View direct and group hospital communication threads.",
    },
    {
        "code": "hospital:communication.manage",
        "name": "Manage Hospital Communications",
        "description": "Create conversations, send messages, and manage communication templates.",
    },
    {
        "code": "hospital:communication.supervise",
        "name": "Supervise Hospital Communications",
        "description": "Perform supervisory communication actions including participant and template governance.",
    },
    {
        "code": "hospital:broadcast.manage",
        "name": "Manage Hospital Broadcasts",
        "description": "Create and manage emergency broadcasts and responses.",
    },

    # Communication domain (canonical permission-driven frontend contract)
    {
        "code": "communication:chat.view",
        "name": "View Chat Conversations",
        "description": "View chat conversations, message history, and unread counters.",
    },
    {
        "code": "communication:chat.conversation.create",
        "name": "Create Chat Conversations",
        "description": "Create or open direct chat conversations.",
    },
    {
        "code": "communication:chat.message.send",
        "name": "Send Chat Messages",
        "description": "Send chat messages and conversation replies.",
    },
    {
        "code": "communication:chat.message.read",
        "name": "Read Chat Messages",
        "description": "Mark chat conversations and messages as read.",
    },
    {
        "code": "communication:chat.message.delete",
        "name": "Delete Chat Messages",
        "description": "Delete chat messages for self or all participants when allowed.",
    },
    {
        "code": "communication:chat.conversation.delete",
        "name": "Delete Chat Conversations",
        "description": "Delete or hide chat conversations for the current user context.",
    },
    {
        "code": "communication:chat.audit.view",
        "name": "View Chat Audit Events",
        "description": "View chat audit metadata for authorized conversations.",
    },
    {
        "code": "communication:chat.export",
        "name": "Export Chat Conversations",
        "description": "Export authorized chat conversations in JSON or CSV formats.",
    },
    {
        "code": "communication:chat.attachment.upload",
        "name": "Upload Chat Attachments",
        "description": "Upload files as chat message attachments.",
    },
    {
        "code": "communication:conversation.view",
        "name": "View Conversation Module",
        "description": "View communication conversations, participants, and messages.",
    },
    {
        "code": "communication:conversation.manage",
        "name": "Manage Conversation Module",
        "description": "Manage conversation lifecycle, participants, and message sending.",
    },
    {
        "code": "communication:template.view",
        "name": "View Message Templates",
        "description": "View reusable communication templates.",
    },
    {
        "code": "communication:template.manage",
        "name": "Manage Message Templates",
        "description": "Create, update, and delete communication templates.",
    },
    {
        "code": "communication:broadcast.view",
        "name": "View Broadcasts",
        "description": "View broadcast messages and unread broadcast status.",
    },
    {
        "code": "communication:broadcast.send",
        "name": "Send Broadcasts",
        "description": "Create and send broadcast messages.",
    },
    {
        "code": "communication:broadcast.read",
        "name": "Read Broadcasts",
        "description": "Mark broadcast messages as read.",
    },
    {
        "code": "communication:broadcast.respond",
        "name": "Respond to Broadcasts",
        "description": "Submit emergency responses to broadcasts.",
    },
    {
        "code": "communication:broadcast.response.view",
        "name": "View Broadcast Responses",
        "description": "View responses submitted for emergency broadcasts.",
    },
    {
        "code": "communication:broadcast.manage",
        "name": "Manage Broadcasts",
        "description": "Manage broadcast lifecycle actions such as close and delete.",
    },
    {
        "code": "communication:notification.view",
        "name": "View Notifications",
        "description": "View user notifications.",
    },
    {
        "code": "communication:notification.read",
        "name": "Mark Notifications Read",
        "description": "Mark one or all notifications as read.",
    },

    # Reporting, dashboard, and files
    {
        "code": "reports:view",
        "name": "View Reports",
        "description": "View report screens and summary report data.",
    },
    {
        "code": "reports:export",
        "name": "Export Reports",
        "description": "Export report data for external use.",
    },
    {
        "code": "reports:payment.view",
        "name": "View Payment Reports",
        "description": "View payment report summaries and settlement metrics.",
    },
    {
        "code": "reports:payment.export",
        "name": "Export Payment Reports",
        "description": "Export payment reports and reconciliation results.",
    },
    {
        "code": "reports:analytics.view",
        "name": "View Analytics Reports",
        "description": "View analytics-focused reports and trend summaries.",
    },
    {
        "code": "dashboard:view",
        "name": "View Dashboard",
        "description": "Access dashboard routes and core dashboard layout.",
    },
    {
        "code": "dashboard:widget.inventory.view",
        "name": "View Inventory Dashboard Widgets",
        "description": "View inventory-focused dashboard widgets.",
    },
    {
        "code": "dashboard:widget.requests.view",
        "name": "View Request Dashboard Widgets",
        "description": "View request workflow dashboard widgets.",
    },
    {
        "code": "dashboard:widget.transport.view",
        "name": "View Transport Dashboard Widgets",
        "description": "View transport and shipment dashboard widgets.",
    },
    {
        "code": "dashboard:widget.communication.view",
        "name": "View Communication Dashboard Widgets",
        "description": "View communication and notification dashboard widgets.",
    },
    {
        "code": "dashboard:widget.ml.view",
        "name": "View ML Dashboard Widgets",
        "description": "View ML and forecasting dashboard widgets.",
    },
    {
        "code": "files:attachment.view",
        "name": "View Attachments",
        "description": "View attachment metadata and attachment files when authorized.",
    },
    {
        "code": "files:attachment.upload",
        "name": "Upload Attachments",
        "description": "Upload file attachments in supported modules.",
    },
    {
        "code": "files:attachment.delete",
        "name": "Delete Attachments",
        "description": "Delete attachment records and underlying files when authorized.",
    },

    # ML and AI lifecycle
    {
        "code": "ml:forecast.view",
        "name": "View Forecast Results",
        "description": "View forecast outputs and forecast summaries.",
    },
    {
        "code": "ml:outbreak.view",
        "name": "View Outbreak Results",
        "description": "View outbreak predictions and outbreak summaries.",
    },
    {
        "code": "ml:suggestion.view",
        "name": "View ML Suggestions",
        "description": "View ML-generated request suggestions and neighbor recommendations.",
    },
    {
        "code": "ml:job.view",
        "name": "View ML Jobs",
        "description": "View ML job records, status, events, and result references.",
    },
    {
        "code": "ml:job.manage",
        "name": "Manage ML Jobs",
        "description": "Create, retry, and cancel ML jobs.",
    },
    {
        "code": "ml:schedule.manage",
        "name": "Manage ML Schedules",
        "description": "Create, update, activate, and deactivate ML schedules.",
    },
    {
        "code": "ml:facility.settings.manage",
        "name": "Manage ML Facility Settings",
        "description": "Update facility-level ML settings and thresholds.",
    },
    {
        "code": "ml:dataset.review",
        "name": "Review ML Training Datasets",
        "description": "Review, approve, and reject generated ML training datasets.",
    },
    {
        "code": "ml:training.manage",
        "name": "Manage ML Training Jobs",
        "description": "Create and monitor ML training jobs for model lifecycle workflows.",
    },
    {
        "code": "ml:model_version.manage",
        "name": "Manage ML Model Versions",
        "description": "Review and approve ML model versions before activation.",
    },
    {
        "code": "ml:model_version.activate",
        "name": "Activate ML Model Versions",
        "description": "Activate, deactivate, and rollback active prediction model versions.",
    },
    {
        "code": "ml:model_version.rollback",
        "name": "Rollback ML Model Versions",
        "description": "Rollback active ML model versions to a previous approved version.",
    },
]


def seed_permissions(apps, schema_editor):
    Permission = apps.get_model("staff", "Permission")

    for entry in PERMISSIONS:
        Permission.objects.update_or_create(
            code=entry["code"],
            defaults={
                "name": entry["name"],
                "description": entry["description"],
                "is_active": True,
            },
        )


def noop_reverse(apps, schema_editor):
    # Intentionally no-op to avoid destructive permission deletions on rollback.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_hospitalrole_hospitalrolepermission_platformrole_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_permissions, noop_reverse),
    ]
