# Generated by Django 4.2.16 on 2026-04-07

from django.db import migrations


ML_OUTPUT_PERMISSIONS = (
    {
        "code": "ml:forecast.view",
        "name": "View Forecast Results",
        "description": "View model forecast outputs for authorized facilities.",
    },
    {
        "code": "ml:outbreak.view",
        "name": "View Outbreak Results",
        "description": "View model outbreak outputs for authorized facilities.",
    },
)

HOSPITAL_ADMIN_ROLE_NAMES = ("HEALTHCARE_ADMIN", "HOSPITAL_ADMIN")


def grant_ml_output_permissions_to_hospital_admin(apps, schema_editor):
    Permission = apps.get_model("staff", "Permission")
    HospitalRole = apps.get_model("staff", "HospitalRole")
    HospitalRolePermission = apps.get_model("staff", "HospitalRolePermission")
    Role = apps.get_model("staff", "Role")
    RolePermission = apps.get_model("staff", "RolePermission")

    permission_lookup = {}
    for row in ML_OUTPUT_PERMISSIONS:
        permission, _ = Permission.objects.update_or_create(
            code=row["code"],
            defaults={
                "name": row["name"],
                "description": row["description"],
                "is_active": True,
            },
        )
        permission_lookup[row["code"]] = permission

    permissions = list(permission_lookup.values())
    if not permissions:
        return

    hospital_roles = HospitalRole.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES, is_active=True)
    for hospital_role in hospital_roles.iterator():
        existing_ids = set(
            HospitalRolePermission.objects.filter(
                hospital_role=hospital_role,
                permission__in=permissions,
            ).values_list("permission_id", flat=True)
        )
        for permission in permissions:
            if permission.id in existing_ids:
                continue
            HospitalRolePermission.objects.create(
                hospital_role=hospital_role,
                permission=permission,
            )

    legacy_roles = Role.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES)
    for role in legacy_roles.iterator():
        existing_ids = set(
            RolePermission.objects.filter(
                role=role,
                permission__in=permissions,
            ).values_list("permission_id", flat=True)
        )
        for permission in permissions:
            if permission.id in existing_ids:
                continue
            RolePermission.objects.create(
                role=role,
                permission=permission,
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_seed_full_permission_catalog"),
    ]

    operations = [
        migrations.RunPython(grant_ml_output_permissions_to_hospital_admin, noop_reverse),
    ]
