# Generated by Django 4.2.16 on 2026-04-07

from django.db import migrations


ML_SCHEDULE_PERMISSION = {
    "code": "ml:schedule.manage",
    "name": "Manage ML Schedules",
    "description": "Create, update, activate, and deactivate ML schedules.",
}

HOSPITAL_ADMIN_ROLE_NAMES = ("HEALTHCARE_ADMIN", "HOSPITAL_ADMIN")


def grant_ml_schedule_permission_to_hospital_admin(apps, schema_editor):
    Permission = apps.get_model("staff", "Permission")
    HospitalRole = apps.get_model("staff", "HospitalRole")
    HospitalRolePermission = apps.get_model("staff", "HospitalRolePermission")
    Role = apps.get_model("staff", "Role")
    RolePermission = apps.get_model("staff", "RolePermission")

    permission, _ = Permission.objects.update_or_create(
        code=ML_SCHEDULE_PERMISSION["code"],
        defaults={
            "name": ML_SCHEDULE_PERMISSION["name"],
            "description": ML_SCHEDULE_PERMISSION["description"],
            "is_active": True,
        },
    )

    hospital_roles = HospitalRole.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES, is_active=True)
    for hospital_role in hospital_roles.iterator():
        HospitalRolePermission.objects.get_or_create(
            hospital_role=hospital_role,
            permission=permission,
        )

    legacy_roles = Role.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES)
    for role in legacy_roles.iterator():
        RolePermission.objects.get_or_create(
            role=role,
            permission=permission,
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_grant_ml_output_permissions_to_hospital_admin"),
    ]

    operations = [
        migrations.RunPython(grant_ml_schedule_permission_to_hospital_admin, noop_reverse),
    ]
