# Generated by Django 4.2.16 on 2026-04-07

from django.db import migrations


SALES_PERMISSIONS = (
    {
        "code": "hospital:sales.view",
        "name": "View Sales Records",
        "description": "View operational sales resources and sale records.",
    },
    {
        "code": "hospital:sales.manage",
        "name": "Manage Sales Records",
        "description": "Create and manage operational sales records.",
    },
)

HOSPITAL_ADMIN_ROLE_NAMES = ("HEALTHCARE_ADMIN", "HOSPITAL_ADMIN")


def grant_sales_permissions_to_hospital_admin(apps, schema_editor):
    Permission = apps.get_model("staff", "Permission")
    HospitalRole = apps.get_model("staff", "HospitalRole")
    HospitalRolePermission = apps.get_model("staff", "HospitalRolePermission")
    Role = apps.get_model("staff", "Role")
    RolePermission = apps.get_model("staff", "RolePermission")

    permissions = []
    for row in SALES_PERMISSIONS:
        permission, _ = Permission.objects.update_or_create(
            code=row["code"],
            defaults={
                "name": row["name"],
                "description": row["description"],
                "is_active": True,
            },
        )
        permissions.append(permission)

    hospital_roles = HospitalRole.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES, is_active=True)
    for hospital_role in hospital_roles.iterator():
        for permission in permissions:
            HospitalRolePermission.objects.get_or_create(
                hospital_role=hospital_role,
                permission=permission,
            )

    legacy_roles = Role.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES)
    for role in legacy_roles.iterator():
        for permission in permissions:
            RolePermission.objects.get_or_create(
                role=role,
                permission=permission,
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_grant_ml_schedule_permission_to_hospital_admin"),
    ]

    operations = [
        migrations.RunPython(grant_sales_permissions_to_hospital_admin, noop_reverse),
    ]
