# Generated by Django 4.2.16 on 2026-04-08

from django.db import migrations


HOSPITAL_REQUEST_PERMISSIONS = (
    {
        "code": "hospital:update_request.submit",
        "name": "Submit Hospital Update Requests",
        "description": "Submit hospital identity and integration update requests for administrative review.",
    },
    {
        "code": "hospital:offboarding.request",
        "name": "Request Hospital Offboarding",
        "description": "Submit hospital offboarding requests for administrative review.",
    },
)

PLATFORM_REVIEW_PERMISSIONS = (
    {
        "code": "platform:hospital.update.review",
        "name": "Review Hospital Update Requests",
        "description": "Review, approve, and reject hospital profile and integration update requests.",
    },
    {
        "code": "platform:hospital.offboarding.review",
        "name": "Review Hospital Offboarding Requests",
        "description": "Review, approve, and reject hospital offboarding requests.",
    },
)

HOSPITAL_ADMIN_ROLE_NAMES = ("HEALTHCARE_ADMIN", "HOSPITAL_ADMIN")
SYSTEM_ADMIN_ROLE_NAMES = ("SUPER_ADMIN", "PLATFORM_ADMIN", "SYSTEM_ADMIN")


def grant_lifecycle_request_permissions(apps, schema_editor):
    Permission = apps.get_model("staff", "Permission")
    HospitalRole = apps.get_model("staff", "HospitalRole")
    HospitalRolePermission = apps.get_model("staff", "HospitalRolePermission")
    PlatformRole = apps.get_model("staff", "PlatformRole")
    PlatformRolePermission = apps.get_model("staff", "PlatformRolePermission")
    Role = apps.get_model("staff", "Role")
    RolePermission = apps.get_model("staff", "RolePermission")

    permission_by_code = {}
    for row in (*HOSPITAL_REQUEST_PERMISSIONS, *PLATFORM_REVIEW_PERMISSIONS):
        permission, _ = Permission.objects.update_or_create(
            code=row["code"],
            defaults={
                "name": row["name"],
                "description": row["description"],
                "is_active": True,
            },
        )
        permission_by_code[row["code"]] = permission

    hospital_permissions = [permission_by_code[row["code"]] for row in HOSPITAL_REQUEST_PERMISSIONS]
    platform_permissions = [permission_by_code[row["code"]] for row in PLATFORM_REVIEW_PERMISSIONS]

    hospital_roles = HospitalRole.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES, is_active=True)
    for hospital_role in hospital_roles.iterator():
        for permission in hospital_permissions:
            HospitalRolePermission.objects.get_or_create(
                hospital_role=hospital_role,
                permission=permission,
            )

    platform_roles = PlatformRole.objects.filter(name__in=SYSTEM_ADMIN_ROLE_NAMES, is_active=True)
    for platform_role in platform_roles.iterator():
        for permission in platform_permissions:
            PlatformRolePermission.objects.get_or_create(
                platform_role=platform_role,
                permission=permission,
            )

    legacy_hospital_roles = Role.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES)
    for role in legacy_hospital_roles.iterator():
        for permission in hospital_permissions:
            RolePermission.objects.get_or_create(
                role=role,
                permission=permission,
            )

    legacy_system_roles = Role.objects.filter(name__in=SYSTEM_ADMIN_ROLE_NAMES)
    for role in legacy_system_roles.iterator():
        for permission in platform_permissions:
            RolePermission.objects.get_or_create(
                role=role,
                permission=permission,
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_grant_sales_permissions_to_hospital_admin"),
    ]

    operations = [
        migrations.RunPython(grant_lifecycle_request_permissions, noop_reverse),
    ]
