# Generated by Django 4.2.16 on 2026-04-09

from django.db import migrations


REQUEST_TRANSPORT_PERMISSIONS = (
    {
        "code": "hospital:request.dispatch",
        "name": "Dispatch Requests",
        "description": "Dispatch approved resource requests for transport workflows.",
    },
    {
        "code": "hospital:request.reserve",
        "name": "Reserve Request Inventory",
        "description": "Reserve supplier inventory for approved requests.",
    },
    {
        "code": "hospital:request.transfer.confirm",
        "name": "Confirm Transfers",
        "description": "Confirm transfer completion and receiving quantities.",
    },
    {
        "code": "hospital:request.delivery.confirm",
        "name": "Confirm Deliveries",
        "description": "Confirm request deliveries via token-based handover workflows.",
    },
    {
        "code": "hospital:request.return.verify",
        "name": "Verify Request Returns",
        "description": "Verify request return flows and return tokens.",
    },
    {
        "code": "hospital:request.expire",
        "name": "Expire Requests",
        "description": "Run request expiration workflows for overdue requests.",
    },
    {
        "code": "hospital:transport.view",
        "name": "View Transport Operations",
        "description": "View shipment, dispatch, and transport tracking operations.",
    },
    {
        "code": "hospital:transport.create",
        "name": "Create Transport Operations",
        "description": "Create shipment and transport records.",
    },
    {
        "code": "hospital:transport.update",
        "name": "Update Transport Operations",
        "description": "Update shipment status and transport operation metadata.",
    },
    {
        "code": "hospital:transport.assign",
        "name": "Assign Transport Resources",
        "description": "Assign riders and related transport resources.",
    },
    {
        "code": "hospital:transport.track",
        "name": "Track Transport Operations",
        "description": "Add and view shipment tracking events.",
    },
)

HOSPITAL_ADMIN_ROLE_NAMES = ("HEALTHCARE_ADMIN", "HOSPITAL_ADMIN")


def grant_request_transport_permissions_to_hospital_admin(apps, schema_editor):
    Permission = apps.get_model("staff", "Permission")
    HospitalRole = apps.get_model("staff", "HospitalRole")
    HospitalRolePermission = apps.get_model("staff", "HospitalRolePermission")
    Role = apps.get_model("staff", "Role")
    RolePermission = apps.get_model("staff", "RolePermission")

    permission_lookup = {}
    for row in REQUEST_TRANSPORT_PERMISSIONS:
        permission, _ = Permission.objects.update_or_create(
            code=row["code"],
            defaults={
                "name": row["name"],
                "description": row["description"],
                "is_active": True,
            },
        )
        permission_lookup[row["code"]] = permission

    permissions = [permission_lookup[row["code"]] for row in REQUEST_TRANSPORT_PERMISSIONS]

    hospital_roles = HospitalRole.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES, is_active=True)
    for hospital_role in hospital_roles.iterator():
        for permission in permissions:
            HospitalRolePermission.objects.get_or_create(
                hospital_role=hospital_role,
                permission=permission,
            )

    legacy_roles = Role.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES)
    for role in legacy_roles.iterator():
        for permission in permissions:
            RolePermission.objects.get_or_create(
                role=role,
                permission=permission,
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0010_grant_hospital_lifecycle_request_permissions"),
    ]

    operations = [
        migrations.RunPython(grant_request_transport_permissions_to_hospital_admin, noop_reverse),
    ]
