# Generated by Django 4.2.16 on 2026-04-09

from django.db import migrations


LEGACY_REQUEST_COMPAT_PERMISSIONS = (
    {
        "code": "share.request.create",
        "name": "Create Share Requests (Legacy)",
        "description": "Legacy compatibility permission for creating resource share requests.",
    },
    {
        "code": "share.request.approve",
        "name": "Approve Share Requests (Legacy)",
        "description": "Legacy compatibility permission for approving resource share requests.",
    },
    {
        "code": "inventory.batch.view",
        "name": "View Inventory Batches (Legacy)",
        "description": "Legacy compatibility permission for viewing inventory batch details.",
    },
    {
        "code": "inventory.cost.view",
        "name": "View Inventory Costs (Legacy)",
        "description": "Legacy compatibility permission for viewing inventory costs.",
    },
)

HOSPITAL_ADMIN_ROLE_NAMES = ("HEALTHCARE_ADMIN", "HOSPITAL_ADMIN")


def grant_legacy_request_compat_permissions_to_hospital_admin(apps, schema_editor):
    Permission = apps.get_model("staff", "Permission")
    HospitalRole = apps.get_model("staff", "HospitalRole")
    HospitalRolePermission = apps.get_model("staff", "HospitalRolePermission")
    Role = apps.get_model("staff", "Role")
    RolePermission = apps.get_model("staff", "RolePermission")

    permission_lookup = {}
    for row in LEGACY_REQUEST_COMPAT_PERMISSIONS:
        permission, _ = Permission.objects.update_or_create(
            code=row["code"],
            defaults={
                "name": row["name"],
                "description": row["description"],
                "is_active": True,
            },
        )
        permission_lookup[row["code"]] = permission

    permissions = [permission_lookup[row["code"]] for row in LEGACY_REQUEST_COMPAT_PERMISSIONS]

    hospital_roles = HospitalRole.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES, is_active=True)
    for hospital_role in hospital_roles.iterator():
        for permission in permissions:
            HospitalRolePermission.objects.get_or_create(
                hospital_role=hospital_role,
                permission=permission,
            )

    legacy_roles = Role.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES)
    for role in legacy_roles.iterator():
        for permission in permissions:
            RolePermission.objects.get_or_create(
                role=role,
                permission=permission,
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0011_grant_request_transport_permissions_to_hospital_admin"),
    ]

    operations = [
        migrations.RunPython(grant_legacy_request_compat_permissions_to_hospital_admin, noop_reverse),
    ]
