# Generated by Django 4.2.16 on 2026-04-09

from django.db import migrations


INVENTORY_PRICE_UPDATE_PERMISSIONS = (
    {
        "code": "hospital:catalog.view",
        "name": "View Resource Catalog",
        "description": "View resource catalog entries for a hospital.",
    },
    {
        "code": "hospital:catalog.manage",
        "name": "Manage Resource Catalog",
        "description": "Create, update, and delete resource catalog entries.",
    },
    {
        "code": "hospital:inventory.view",
        "name": "View Hospital Inventory",
        "description": "View hospital inventory and catalog data.",
    },
    {
        "code": "hospital:inventory.edit",
        "name": "Edit Hospital Inventory",
        "description": "Edit hospital inventory quantities and item metadata.",
    },
    {
        "code": "hospital:inventory.manage",
        "name": "Manage Hospital Inventory",
        "description": "Manage hospital inventory lifecycle operations.",
    },
    {
        "code": "hospital:inventory.supervise",
        "name": "Supervise Hospital Inventory",
        "description": "Perform supervisory inventory controls and policy updates.",
    },
    {
        "code": "hospital:inventory.import",
        "name": "Import Inventory Data",
        "description": "Validate and commit inventory imports from CSV and integration pipelines.",
    },
)

HOSPITAL_ADMIN_ROLE_NAMES = ("HEALTHCARE_ADMIN", "HOSPITAL_ADMIN")


def grant_inventory_price_update_permissions_to_hospital_admin(apps, schema_editor):
    Permission = apps.get_model("staff", "Permission")
    HospitalRole = apps.get_model("staff", "HospitalRole")
    HospitalRolePermission = apps.get_model("staff", "HospitalRolePermission")
    Role = apps.get_model("staff", "Role")
    RolePermission = apps.get_model("staff", "RolePermission")

    permission_lookup = {}
    for row in INVENTORY_PRICE_UPDATE_PERMISSIONS:
        permission, _ = Permission.objects.update_or_create(
            code=row["code"],
            defaults={
                "name": row["name"],
                "description": row["description"],
                "is_active": True,
            },
        )
        permission_lookup[row["code"]] = permission

    permissions = [permission_lookup[row["code"]] for row in INVENTORY_PRICE_UPDATE_PERMISSIONS]

    hospital_roles = HospitalRole.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES, is_active=True)
    for hospital_role in hospital_roles.iterator():
        for permission in permissions:
            HospitalRolePermission.objects.get_or_create(
                hospital_role=hospital_role,
                permission=permission,
            )

    legacy_roles = Role.objects.filter(name__in=HOSPITAL_ADMIN_ROLE_NAMES)
    for role in legacy_roles.iterator():
        for permission in permissions:
            RolePermission.objects.get_or_create(
                role=role,
                permission=permission,
            )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0013_grant_hospital_update_request_view_permissions"),
    ]

    operations = [
        migrations.RunPython(grant_inventory_price_update_permissions_to_hospital_admin, noop_reverse),
    ]
