version: '3.8'

services:
  hospital_3_db:
    image: mariadb:10.11
    container_name: hospital_3_db
    environment:
      MYSQL_ROOT_PASSWORD: root2026
      MYSQL_DATABASE: hospital_3_db
      MYSQL_USER: hospital3user
      MYSQL_PASSWORD: hospital3pass
    ports:
      - "3362:3306"
    volumes:
      - hospital_3_data:/var/lib/mysql
      - ./sql_scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  hospital_3_data: