# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("password_reset", "Password Reset"),
                            ("hospital_created", "Hospital Created"),
                            ("hospital_verified", "Hospital Verified"),
                            ("hospital_suspended", "Hospital Suspended"),
                            ("staff_invited", "Staff Invited"),
                            ("invitation_accepted", "Invitation Accepted"),
                            ("role_assigned", "Role Assigned"),
                            ("role_revoked", "Role Revoked"),
                            ("inventory_adjusted", "Inventory Adjusted"),
                            ("request_created", "Request Created"),
                            ("request_approved", "Request Approved"),
                            ("request_rejected", "Request Rejected"),
                            ("request_dispatched", "Request Dispatched"),
                            ("request_delivered", "Request Delivered"),
                            ("request_cancelled", "Request Cancelled"),
                            ("shipment_created", "Shipment Created"),
                            ("shipment_status_updated", "Shipment Status Updated"),
                            ("broadcast_sent", "Broadcast Sent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, help_text="PK of the affected object", null=True)),
                (
                    "object_type",
                    models.CharField(blank=True, help_text="Model name of the affected object", max_length=100),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_auditlog",
            },
        ),
    ]
