# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0002_initial"),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["event_type", "-created_at"], name="audit_audit_event_t_5dda62_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["actor", "-created_at"], name="audit_audit_actor_i_1175ab_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["hospital", "-created_at"], name="audit_audit_hospita_335108_idx"),
        ),
    ]
