# Generated by Django 4.2.16 on 2026-03-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Failed"),
                    ("password_reset", "Password Reset"),
                    ("hospital_created", "Hospital Created"),
                    ("hospital_verified", "Hospital Verified"),
                    ("hospital_suspended", "Hospital Suspended"),
                    ("hospital_offboarding_requested", "Hospital Offboarding Requested"),
                    ("hospital_offboarding_approved", "Hospital Offboarding Approved"),
                    ("hospital_offboarding_rejected", "Hospital Offboarding Rejected"),
                    ("staff_invited", "Staff Invited"),
                    ("invitation_accepted", "Invitation Accepted"),
                    ("role_assigned", "Role Assigned"),
                    ("role_revoked", "Role Revoked"),
                    ("inventory_adjusted", "Inventory Adjusted"),
                    ("request_created", "Request Created"),
                    ("request_approved", "Request Approved"),
                    ("request_rejected", "Request Rejected"),
                    ("request_dispatched", "Request Dispatched"),
                    ("request_delivered", "Request Delivered"),
                    ("request_cancelled", "Request Cancelled"),
                    ("shipment_created", "Shipment Created"),
                    ("shipment_status_updated", "Shipment Status Updated"),
                    ("broadcast_sent", "Broadcast Sent"),
                ],
                max_length=50,
            ),
        ),
    ]
