# Generated by Django 4.2.16 on 2026-04-03 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0012_hospital_advanced_integration_eligible_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("audit", "0004_alter_auditlog_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizationAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100)),
                ("resource", models.CharField(max_length=150)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorization_audit_logs",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorization_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "indexes": [
                    models.Index(fields=["action", "-timestamp"], name="audit_log_action_cf8063_idx"),
                    models.Index(fields=["user", "-timestamp"], name="audit_log_user_id_79f582_idx"),
                    models.Index(fields=["hospital", "-timestamp"], name="audit_log_hospita_21bff4_idx"),
                ],
            },
        ),
    ]
