# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="user_accounts", through="staff.UserRole", to="staff.role"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="staff",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_account",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
