# Generated by Django 4.2.16 on 2026-03-31 04:21

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_passwordresettoken_hash_and_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("is_active", True)),
                name="uniq_auth_user_email_active_ci",
            ),
        ),
    ]
