# Generated by Django 5.2.6 on 2026-04-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_useraccount_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="access_mode",
            field=models.CharField(
                choices=[("UI", "UI Client"), ("API", "API Client")],
                db_index=True,
                default="UI",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="context_domain",
            field=models.CharField(
                blank=True,
                choices=[("HEALTHCARE", "Healthcare"), ("PLATFORM", "Platform")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
    ]
