# Generated by Django 5.2.6 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_useraccount_context_domain_and_access_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="users/profile-pictures/"),
        ),
    ]
