# Generated by Django 5.2.5 on 2026-04-02

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitals", "0010_hospital_inventory_last_sync_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyCSVImportJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[("SALES", "Sales"), ("STAFF", "Staff"), ("MOVEMENT", "Movement")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                (
                    "conflict_policy",
                    models.CharField(
                        choices=[("REJECT", "Reject"), ("OVERWRITE", "Overwrite")],
                        default="REJECT",
                        max_length=20,
                    ),
                ),
                (
                    "locked_period_policy",
                    models.CharField(
                        choices=[("REJECT", "Reject"), ("SKIP", "Skip")],
                        default="REJECT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLYING", "Applying"),
                            ("APPLIED", "Applied"),
                            ("PARTIALLY_APPLIED", "Partially Applied"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="APPLYING",
                        max_length=30,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("applied_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("conflict_rows", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_csv_import_jobs",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_csv_import_jobs_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_csv_import_job",
                "indexes": [
                    models.Index(fields=["facility", "dataset_type", "-created_at"], name="pharmacy_cs_facilit_1d7198_idx"),
                    models.Index(fields=["status", "-updated_at"], name="pharmacy_cs_status_c006f3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PharmacyCSVImportConflict",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("row_number", models.PositiveIntegerField(default=0)),
                ("conflict_key", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("existing_record", models.JSONField(blank=True, default=dict)),
                ("incoming_record", models.JSONField(blank=True, default=dict)),
                (
                    "resolution",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("OVERWRITTEN", "Overwritten"), ("SKIPPED", "Skipped")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="pharmacy_csv.pharmacycsvimportjob",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_csv_import_conflict",
                "indexes": [
                    models.Index(fields=["import_job", "row_number"], name="pharmacy_cs_import__38f928_idx"),
                    models.Index(fields=["conflict_key"], name="pharmacy_cs_conflic_9871e7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PharmacyCSVImportError",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("row_number", models.PositiveIntegerField(default=0)),
                ("field_name", models.CharField(blank=True, max_length=80)),
                ("error_code", models.CharField(max_length=80)),
                ("error_message", models.TextField()),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="pharmacy_csv.pharmacycsvimportjob",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_csv_import_error",
                "indexes": [
                    models.Index(fields=["import_job", "row_number"], name="pharmacy_cs_import__bdc9c9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PharmacyCSVValidationContext",
            fields=[
                ("file_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[("SALES", "Sales"), ("STAFF", "Staff"), ("MOVEMENT", "Movement")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("expected_schema", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("conflicts", models.JSONField(blank=True, default=list)),
                ("sample_rows", models.JSONField(blank=True, default=list)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_csv_validation_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_csv_validation_contexts",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_csv_validation_context",
                "indexes": [
                    models.Index(
                        fields=["facility", "dataset_type", "-created_at"],
                        name="pharmacy_cs_facilit_3a6162_idx",
                    ),
                    models.Index(fields=["file_hash"], name="pharmacy_cs_file_ha_c0ac1a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PharmacyCSVRowVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[("SALES", "Sales"), ("STAFF", "Staff"), ("MOVEMENT", "Movement")],
                        max_length=20,
                    ),
                ),
                ("conflict_key", models.CharField(max_length=255)),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_csv_row_versions",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "last_import_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="row_versions",
                        to="pharmacy_csv.pharmacycsvimportjob",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_csv_row_version",
                "indexes": [
                    models.Index(fields=["facility", "dataset_type"], name="pharmacy_cs_facilit_b0deab_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pharmacycsvimportjob",
            constraint=models.UniqueConstraint(
                condition=~django.db.models.expressions.Q(("idempotency_key", "")),
                fields=("facility", "dataset_type", "idempotency_key"),
                name="uniq_pharmacy_csv_import_job_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="pharmacycsvrowversion",
            constraint=models.UniqueConstraint(
                fields=("facility", "dataset_type", "conflict_key"),
                name="uniq_pharmacy_csv_row_version_key",
            ),
        ),
    ]
