# Generated by Django 4.2.16 on 2026-04-02 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0011_hospitalregistrationrequest_api_check_results_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pharmacy_csv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyCSVChatSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "dataset_type",
                    models.CharField(
                        choices=[("SALES", "Sales"), ("STAFF", "Staff"), ("MOVEMENT", "Movement")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_csv_chat_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_csv_chat_sessions",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "validation_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="pharmacy_csv.pharmacycsvvalidationcontext",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_csv_chat_session",
            },
        ),
        migrations.CreateModel(
            name="PharmacyCSVChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "User"), ("ASSISTANT", "Assistant"), ("SYSTEM", "System")], max_length=20
                    ),
                ),
                ("content", models.TextField()),
                ("out_of_scope", models.BooleanField(default=False)),
                ("message_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="pharmacy_csv.pharmacycsvchatsession",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy_csv_chat_message",
            },
        ),
        migrations.AddIndex(
            model_name="pharmacycsvchatsession",
            index=models.Index(
                fields=["facility", "dataset_type", "-created_at"], name="pharmacy_cs_facilit_283854_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacycsvchatsession",
            index=models.Index(fields=["validation_context", "-created_at"], name="pharmacy_cs_validat_a1ea0c_idx"),
        ),
        migrations.AddIndex(
            model_name="pharmacycsvchatsession",
            index=models.Index(fields=["status", "-updated_at"], name="pharmacy_cs_status_f9045b_idx"),
        ),
        migrations.AddIndex(
            model_name="pharmacycsvchatmessage",
            index=models.Index(fields=["session", "created_at"], name="pharmacy_cs_session_e27aa3_idx"),
        ),
        migrations.AddIndex(
            model_name="pharmacycsvchatmessage",
            index=models.Index(fields=["role", "-created_at"], name="pharmacy_cs_role_a792d8_idx"),
        ),
    ]
