# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shipments", "0001_initial"),
        ("resources", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospitals", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity_requested", models.PositiveIntegerField()),
                ("quantity_approved", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("critical", "Critical")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("needed_by", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="resources.resourcecatalog",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requesting_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_requests",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "supplying_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_requests",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "requests_resourcerequest",
            },
        ),
        migrations.CreateModel(
            name="ResourceRequestApproval",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "decision",
                    models.CharField(choices=[("approved", "Approved"), ("rejected", "Rejected")], max_length=20),
                ),
                ("quantity_approved", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval",
                        to="resource_requests.resourcerequest",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "requests_approval",
            },
        ),
        migrations.CreateModel(
            name="DispatchEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notes", models.TextField(blank=True)),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_event",
                        to="resource_requests.resourcerequest",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatch_events",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "requests_dispatchevent",
            },
        ),
        migrations.CreateModel(
            name="DeliveryToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=128, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_token",
                        to="resource_requests.resourcerequest",
                    ),
                ),
            ],
            options={
                "db_table": "requests_deliverytoken",
            },
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity_received", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_event",
                        to="resource_requests.resourcerequest",
                    ),
                ),
            ],
            options={
                "db_table": "requests_deliveryevent",
            },
        ),
        migrations.AddIndex(
            model_name="resourcerequest",
            index=models.Index(fields=["status", "-created_at"], name="requests_re_status_001b00_idx"),
        ),
        migrations.AddIndex(
            model_name="resourcerequest",
            index=models.Index(fields=["requesting_hospital", "status"], name="requests_re_request_3d883b_idx"),
        ),
        migrations.AddIndex(
            model_name="resourcerequest",
            index=models.Index(fields=["supplying_hospital", "status"], name="requests_re_supplyi_b64f28_idx"),
        ),
    ]
