# Generated by Django 4.2.16 on 2026-03-15 15:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resource_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcerequest",
            name="payment_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("pending_manual_verification", "Pending Manual Verification"),
                    ("paid", "Paid"),
                ],
                default="unpaid",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="price_snapshot",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AlterField(
            model_name="resourcerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("dispatched", "Dispatched"),
                    ("fulfilled", "Fulfilled"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
