# Generated by Django 4.2.16 on 2026-03-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0009_hospital_facility_metadata"),
        ("resources", "0004_rename_resources_r_invento_5f09be_idx_resources_r_invento_44bba6_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource_requests", "0002_resourcerequest_payment_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalInventoryAPICallLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation", models.CharField(max_length=40)),
                ("endpoint", models.CharField(max_length=500)),
                ("http_method", models.CharField(max_length=10)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("timeout_ms", models.IntegerField(default=10000)),
                ("retry_attempt", models.IntegerField(default=0)),
                (
                    "call_status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("TIMEOUT", "Timeout"),
                            ("FAILED", "Failed"),
                            ("RETRYING", "Retrying"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "requests_externalinventoryapicalllog",
            },
        ),
        migrations.CreateModel(
            name="ExternalInventoryReservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_reservation_id", models.CharField(max_length=150)),
                ("reserved_quantity", models.PositiveIntegerField(default=0)),
                (
                    "reservation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RESERVED", "Reserved"),
                            ("RELEASED", "Released"),
                            ("CONFIRMED_TRANSFER", "Confirmed Transfer"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "requests_externalinventoryreservation",
            },
        ),
        migrations.CreateModel(
            name="InventoryDriftAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("expected_quantity", models.IntegerField()),
                ("reported_quantity", models.IntegerField()),
                ("drift_quantity", models.IntegerField()),
                (
                    "severity",
                    models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], max_length=20),
                ),
                (
                    "alert_status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("ACKNOWLEDGED", "Acknowledged"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "requests_inventorydriftalert",
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayWebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=30)),
                ("event_type", models.CharField(max_length=50)),
                ("provider_transaction_id", models.CharField(blank=True, max_length=150, null=True)),
                ("signature_valid", models.BooleanField(default=False)),
                ("payload", models.JSONField(default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_status", models.CharField(default="PENDING", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "requests_paymentwebhookevent",
            },
        ),
        migrations.CreateModel(
            name="PaymentLedgerEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("RECEIVED", "Received"),
                            ("REFUND_SENT", "Refund Sent"),
                            ("REFUND_RECEIVED", "Refund Received"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "requests_paymentledgerentry",
            },
        ),
        migrations.CreateModel(
            name="PaymentReconciliationRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(default="SSLCOMMERZ", max_length=30)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run_status",
                    models.CharField(
                        choices=[("RUNNING", "Running"), ("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("checked_count", models.IntegerField(default=0)),
                ("corrected_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "requests_paymentreconciliationrun",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("SSLCOMMERZ", "SSLCOMMERZ"), ("OTHER", "Other")], default="SSLCOMMERZ", max_length=30
                    ),
                ),
                ("provider_transaction_id", models.CharField(blank=True, max_length=150, null=True)),
                ("gateway_session_id", models.CharField(blank=True, max_length=150, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BDT", max_length=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUND_PENDING", "Refund Pending"),
                            ("REFUNDED", "Refunded"),
                            ("REFUND_FAILED", "Refund Failed"),
                        ],
                        default="INITIATED",
                        max_length=30,
                    ),
                ),
                ("initiated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("authorized_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_code", models.CharField(blank=True, max_length=80)),
                ("failure_message", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("raw_gateway_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "requests_paymenttransaction",
            },
        ),
        migrations.CreateModel(
            name="RequestOperationIdempotency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("reservation_create", "Reservation Create"),
                            ("payment_initiate", "Payment Initiate"),
                            ("transfer_confirm", "Transfer Confirm"),
                        ],
                        max_length=40,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "requests_operation_idempotency",
            },
        ),
        migrations.CreateModel(
            name="RequestWorkflowAuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action_type", models.CharField(max_length=50)),
                ("action_status", models.CharField(max_length=20)),
                ("actor_type", models.CharField(max_length=20)),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.CharField(blank=True, max_length=128)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "requests_workflowauditlog",
            },
        ),
        migrations.CreateModel(
            name="ResourceRequestReservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reserved_quantity", models.PositiveIntegerField()),
                ("unit_price_at_reservation", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reservation_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RELEASED", "Released"),
                            ("CONSUMED", "Consumed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "requests_resourcerequestreservation",
            },
        ),
        migrations.CreateModel(
            name="ResourceRequestStateTransition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("from_state", models.CharField(max_length=30)),
                ("to_state", models.CharField(max_length=30)),
                ("transition_reason", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "requests_state_transition",
            },
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="allow_partial_fulfillment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="deduplication_key",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="failed_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="payment_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="quantity_reserved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="quantity_transferred",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resourcerequest",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("RESERVED", "Reserved"),
                    ("PAYMENT_PENDING", "Payment Pending"),
                    ("PAYMENT_COMPLETED", "Payment Completed"),
                    ("IN_TRANSIT", "In Transit"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                ],
                db_index=True,
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="resourcerequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("pending_manual_verification", "Pending Manual Verification"),
                    ("paid", "Paid"),
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("REFUND_PENDING", "Refund Pending"),
                    ("REFUNDED", "Refunded"),
                    ("REFUND_FAILED", "Refund Failed"),
                ],
                default="unpaid",
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name="resourcerequest",
            index=models.Index(fields=["workflow_state", "-created_at"], name="requests_re_workflo_d97baf_idx"),
        ),
        migrations.AddField(
            model_name="resourcerequeststatetransition",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_state_transitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resourcerequeststatetransition",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_transitions",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddField(
            model_name="resourcerequestreservation",
            name="inventory_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_reservations",
                to="resources.resourceinventorybatch",
            ),
        ),
        migrations.AddField(
            model_name="resourcerequestreservation",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddField(
            model_name="requestworkflowauditlog",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_audit_logs",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddField(
            model_name="requestoperationidempotency",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idempotency_records",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payer_hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="payments_sent", to="hospitals.hospital"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="receiver_hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="payments_received", to="hospitals.hospital"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_transactions",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationrun",
            index=models.Index(fields=["provider", "-created_at"], name="requests_pa_provide_ea4892_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentreconciliationrun",
            index=models.Index(fields=["run_status", "-created_at"], name="requests_pa_run_sta_f2d794_idx"),
        ),
        migrations.AddField(
            model_name="paymentledgerentry",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_ledger_entries",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddField(
            model_name="paymentledgerentry",
            name="payment_transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="resource_requests.paymenttransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentgatewaywebhookevent",
            index=models.Index(fields=["provider", "provider_transaction_id"], name="requests_pa_provide_c50419_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentgatewaywebhookevent",
            index=models.Index(fields=["processing_status", "-created_at"], name="requests_pa_process_d97958_idx"),
        ),
        migrations.AddField(
            model_name="inventorydriftalert",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_drift_alerts",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddField(
            model_name="inventorydriftalert",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_drift_alerts",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddField(
            model_name="inventorydriftalert",
            name="resource_catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_drift_alerts",
                to="resources.resourcecatalog",
            ),
        ),
        migrations.AddField(
            model_name="externalinventoryreservation",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_reservations",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddField(
            model_name="externalinventoryreservation",
            name="resource_catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_inventory_reservations",
                to="resources.resourcecatalog",
            ),
        ),
        migrations.AddField(
            model_name="externalinventoryreservation",
            name="supplying_hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_inventory_reservations",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddField(
            model_name="externalinventoryapicalllog",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_inventory_api_logs",
                to="hospitals.hospital",
            ),
        ),
        migrations.AddField(
            model_name="externalinventoryapicalllog",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_inventory_api_logs",
                to="resource_requests.resourcerequest",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcerequeststatetransition",
            index=models.Index(fields=["request", "-performed_at"], name="requests_st_request_962b3f_idx"),
        ),
        migrations.AddIndex(
            model_name="resourcerequeststatetransition",
            index=models.Index(fields=["to_state", "-performed_at"], name="requests_st_to_stat_4b5d8d_idx"),
        ),
        migrations.AddIndex(
            model_name="resourcerequestreservation",
            index=models.Index(fields=["request", "reservation_status"], name="requests_re_request_2d627d_idx"),
        ),
        migrations.AddIndex(
            model_name="resourcerequestreservation",
            index=models.Index(
                fields=["inventory_batch", "reservation_status"], name="requests_re_invento_e8a010_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcerequestreservation",
            index=models.Index(fields=["expires_at"], name="requests_re_expires_5dfa07_idx"),
        ),
        migrations.AddIndex(
            model_name="requestworkflowauditlog",
            index=models.Index(fields=["request", "-created_at"], name="requests_wo_request_791e9b_idx"),
        ),
        migrations.AddIndex(
            model_name="requestworkflowauditlog",
            index=models.Index(fields=["action_type", "-created_at"], name="requests_wo_action__f41add_idx"),
        ),
        migrations.AddIndex(
            model_name="requestworkflowauditlog",
            index=models.Index(fields=["correlation_id"], name="requests_wo_correla_dcf312_idx"),
        ),
        migrations.AddIndex(
            model_name="requestoperationidempotency",
            index=models.Index(
                fields=["request", "operation_type", "-created_at"], name="requests_op_request_5dccbc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="requestoperationidempotency",
            constraint=models.UniqueConstraint(
                fields=("operation_type", "idempotency_key"), name="uniq_request_operation_idempotency"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["payer_hospital", "-created_at"], name="requests_pa_payer_h_cee77c_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["receiver_hospital", "-created_at"], name="requests_pa_receive_7679f6_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["payment_status", "-created_at"], name="requests_pa_payment_44e444_idx"),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_transaction_id__isnull", False)),
                fields=("provider", "provider_transaction_id"),
                name="uniq_provider_transaction_id",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydriftalert",
            index=models.Index(
                fields=["hospital", "alert_status", "-detected_at"], name="requests_in_hospita_722c87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorydriftalert",
            index=models.Index(fields=["resource_catalog", "-detected_at"], name="requests_in_resourc_8d3f2a_idx"),
        ),
        migrations.AddIndex(
            model_name="externalinventoryreservation",
            index=models.Index(fields=["request", "reservation_status"], name="requests_ex_request_92edde_idx"),
        ),
        migrations.AddIndex(
            model_name="externalinventoryreservation",
            index=models.Index(fields=["expires_at"], name="requests_ex_expires_6b10f9_idx"),
        ),
        migrations.AddConstraint(
            model_name="externalinventoryreservation",
            constraint=models.UniqueConstraint(
                fields=("supplying_hospital", "external_reservation_id"),
                name="uniq_external_reservation_id_per_hospital",
            ),
        ),
        migrations.AddIndex(
            model_name="externalinventoryapicalllog",
            index=models.Index(fields=["hospital", "-created_at"], name="requests_ex_hospita_bda072_idx"),
        ),
        migrations.AddIndex(
            model_name="externalinventoryapicalllog",
            index=models.Index(fields=["request", "-created_at"], name="requests_ex_request_5df968_idx"),
        ),
        migrations.AddIndex(
            model_name="externalinventoryapicalllog",
            index=models.Index(fields=["operation", "-created_at"], name="requests_ex_operati_199736_idx"),
        ),
    ]
