# Generated by Django 4.2.16 on 2026-04-11 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_shipment_cancel_reason_shipment_dispatch_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource_requests", "0003_externalinventoryapicalllog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverytoken",
            name="intended_receiver_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_tokens_intended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverytoken",
            name="sender_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_tokens_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverytoken",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_tokens",
                to="shipments.shipment",
            ),
        ),
        migrations.AddField(
            model_name="deliverytoken",
            name="workflow_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
