"""URL routes for ML orchestration APIs."""
from django.urls import path

from .views import (
    ActiveModelConfigView,
    FacilitySettingsPatchView,
    LatestForecastFacilityView,
    LatestOutbreakFacilityView,
    MLForecastResultView,
    MLJobCancelView,
    MLJobCollectionView,
    MLJobDetailView,
    MLJobEventsView,
    MLJobRetryView,
    MLOutbreakResultView,
    MLScheduleActivateView,
    MLScheduleCollectionView,
    MLScheduleDeactivateView,
    MLScheduleDetailView,
    MLModelVersionActivateView,
    MLModelVersionApproveView,
    MLModelVersionCollectionView,
    MLModelVersionDeactivateView,
    MLModelVersionDetailView,
    MLModelVersionReviewView,
    MLModelVersionRollbackView,
    MLTrainingDatasetApproveView,
    MLTrainingDatasetCollectionView,
    MLTrainingDatasetDetailView,
    MLTrainingDatasetGenerateView,
    MLTrainingDatasetRejectView,
    MLTrainingJobCollectionView,
    MLTrainingJobDetailView,
    Model1PredictView,
    Model2PredictView,
    RequestSuggestionFacilityView,
    ServerBCallbackView,
    ServerBTrainingCallbackView,
)

urlpatterns = [
    path("model1/predict/", Model1PredictView.as_view(), name="ml-model1-predict"),
    path("model2/predict/", Model2PredictView.as_view(), name="ml-model2-predict"),
    path("jobs/", MLJobCollectionView.as_view(), name="ml-jobs"),
    path("jobs/<uuid:job_id>/", MLJobDetailView.as_view(), name="ml-job-detail"),
    path("jobs/<uuid:job_id>/retry/", MLJobRetryView.as_view(), name="ml-job-retry"),
    path("jobs/<uuid:job_id>/cancel/", MLJobCancelView.as_view(), name="ml-job-cancel"),
    path("jobs/<uuid:job_id>/events/", MLJobEventsView.as_view(), name="ml-job-events"),
    path("jobs/<uuid:job_id>/results/forecast/", MLForecastResultView.as_view(), name="ml-forecast-results"),
    path("jobs/<uuid:job_id>/results/outbreak/", MLOutbreakResultView.as_view(), name="ml-outbreak-results"),
    path("schedules/", MLScheduleCollectionView.as_view(), name="ml-schedules"),
    path("schedules/<uuid:schedule_id>/", MLScheduleDetailView.as_view(), name="ml-schedule-detail"),
    path("schedules/<uuid:schedule_id>/activate/", MLScheduleActivateView.as_view(), name="ml-schedule-activate"),
    path("schedules/<uuid:schedule_id>/deactivate/", MLScheduleDeactivateView.as_view(), name="ml-schedule-deactivate"),
    path("facilities/<uuid:facility_id>/latest-forecast/", LatestForecastFacilityView.as_view(), name="ml-facility-latest-forecast"),
    path("facilities/<uuid:facility_id>/latest-outbreak/", LatestOutbreakFacilityView.as_view(), name="ml-facility-latest-outbreak"),
    path("facilities/<uuid:facility_id>/request-suggestions/", RequestSuggestionFacilityView.as_view(), name="ml-facility-request-suggestions"),
    path("facilities/<uuid:facility_id>/settings/", FacilitySettingsPatchView.as_view(), name="ml-facility-settings-patch"),
    path("training/datasets/generate/", MLTrainingDatasetGenerateView.as_view(), name="ml-training-dataset-generate"),
    path("training/datasets/", MLTrainingDatasetCollectionView.as_view(), name="ml-training-dataset-list"),
    path("training/datasets/<uuid:dataset_id>/", MLTrainingDatasetDetailView.as_view(), name="ml-training-dataset-detail"),
    path("training/datasets/<uuid:dataset_id>/approve/", MLTrainingDatasetApproveView.as_view(), name="ml-training-dataset-approve"),
    path("training/datasets/<uuid:dataset_id>/reject/", MLTrainingDatasetRejectView.as_view(), name="ml-training-dataset-reject"),
    path("training/jobs/", MLTrainingJobCollectionView.as_view(), name="ml-training-job-list-create"),
    path("training/jobs/<uuid:training_job_id>/", MLTrainingJobDetailView.as_view(), name="ml-training-job-detail"),
    path("model-versions/", MLModelVersionCollectionView.as_view(), name="ml-model-version-list"),
    path("model-versions/<uuid:version_id>/", MLModelVersionDetailView.as_view(), name="ml-model-version-detail"),
    path("model-versions/<uuid:version_id>/review/", MLModelVersionReviewView.as_view(), name="ml-model-version-review"),
    path("model-versions/<uuid:version_id>/approve/", MLModelVersionApproveView.as_view(), name="ml-model-version-approve"),
    path("model-versions/<uuid:version_id>/activate/", MLModelVersionActivateView.as_view(), name="ml-model-version-activate"),
    path("model-versions/<uuid:version_id>/deactivate/", MLModelVersionDeactivateView.as_view(), name="ml-model-version-deactivate"),
    path("model-versions/<uuid:version_id>/rollback/", MLModelVersionRollbackView.as_view(), name="ml-model-version-rollback"),
    path("models/active/", ActiveModelConfigView.as_view(), name="ml-active-model-configs"),
    path("callbacks/server-b/", ServerBCallbackView.as_view(), name="ml-server-b-callback"),
    path("training/callbacks/server-b/", ServerBTrainingCallbackView.as_view(), name="ml-training-server-b-callback"),
]
