# Generated by Django 4.2.16 on 2026-03-15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0003_passwordresettoken_hash_and_used"),
        ("communications", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="chat/attachments/%Y/%m/%d")),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=120)),
                ("file_size", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="communications.message",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_chat_attachments",
                        to="authentication.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message_attachment",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(fields=["message", "created_at"], name="chat_messag_message_10f2b3_idx"),
        ),
    ]
