# Generated by Django 4.2.16 on 2026-03-16 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communications", "0002_initial"),
        ("chat", "0002_directconversation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageVisibility",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_states",
                        to="communications.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_visibility_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message_visibility",
                "indexes": [
                    models.Index(fields=["user", "is_deleted"], name="chat_messag_user_id_2e436e_idx"),
                    models.Index(fields=["message", "user"], name="chat_messag_message_a46c99_idx"),
                    models.Index(fields=["message", "is_deleted"], name="chat_messag_message_6fbfb9_idx"),
                ],
                "unique_together": {("message", "user")},
            },
        ),
        migrations.CreateModel(
            name="ConversationVisibility",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_states",
                        to="communications.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_visibility_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_conversation_visibility",
                "indexes": [
                    models.Index(fields=["user", "is_deleted"], name="chat_conver_user_id_103dfd_idx"),
                    models.Index(fields=["conversation", "user"], name="chat_conver_convers_54d36c_idx"),
                ],
                "unique_together": {("conversation", "user")},
            },
        ),
        migrations.CreateModel(
            name="ChatAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("message_sent", "Message Sent"),
                            ("message_deleted", "Message Deleted"),
                            ("conversation_created", "Conversation Created"),
                            ("conversation_deleted", "Conversation Deleted"),
                            ("message_read", "Message Read"),
                        ],
                        max_length=40,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_audit_events",
                        to="communications.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_audit_events",
                        to="communications.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_audit_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event_type", "-created_at"], name="chat_audit__event_t_a368f7_idx"),
                    models.Index(fields=["conversation", "-created_at"], name="chat_audit__convers_bc05d1_idx"),
                    models.Index(fields=["user", "-created_at"], name="chat_audit__user_id_515c6f_idx"),
                ],
            },
        ),
    ]
