# Generated by Django 4.2.16 on 2026-03-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_messagevisibility_conversationvisibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageattachment",
            name="duration_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="encoded_codec",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="media_kind",
            field=models.CharField(
                choices=[("image", "Image"), ("file", "File"), ("voice", "Voice"), ("video", "Video")],
                default="file",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="processing_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                ],
                default="ready",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(fields=["media_kind", "created_at"], name="chat_messag_media_k_e3d93f_idx"),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(fields=["processing_status", "created_at"], name="chat_messag_process_530e19_idx"),
        ),
    ]
