# Generated by Django 4.2.27 on 2026-01-31 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('medication', 'Medication'), ('blood', 'Blood Products'), ('organ', 'Organs'), ('equipment', 'Medical Equipment'), ('bed', 'Hospital Beds')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('requires_cold_chain', models.BooleanField(default=False)),
                ('max_transport_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('regulatory_category', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource Category',
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceHospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_hospital_id', models.UUIDField(help_text='ID from dummy hospital system', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('trust_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint for data synchronization')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource Hospital',
                'verbose_name_plural': 'Resource Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SharedResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_resource_id', models.UUIDField(blank=True, help_text='ID from dummy hospital system', null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('current_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A - Excellent'), ('B', 'Grade B - Good'), ('C', 'Grade C - Fair')], default='A', max_length=1)),
                ('storage_requirements', models.TextField(blank=True)),
                ('visibility_level', models.CharField(choices=[('public', 'Public'), ('network', 'Network'), ('emergency_only', 'Emergency Only'), ('private', 'Private')], default='public', max_length=15)),
                ('is_emergency_stock', models.BooleanField(default=False)),
                ('minimum_reserve', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcecategory')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcehospital')),
            ],
            options={
                'verbose_name': 'Shared Resource',
                'verbose_name_plural': 'Shared Resources',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['hospital', 'category'], name='resources_s_hospita_65f2cf_idx'), models.Index(fields=['visibility_level', 'available_quantity'], name='resources_s_visibil_b8f51b_idx'), models.Index(fields=['expiry_date'], name='resources_s_expiry__a87c84_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventorySyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('emergency', 'Emergency Sync')], default='incremental', max_length=15)),
                ('external_system_type', models.CharField(default='dummy_hospital_system', max_length=100)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('sync_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='in_progress', max_length=15)),
                ('error_details', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_scheduled', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='resources.resourcehospital')),
            ],
            options={
                'verbose_name': 'Inventory Sync Log',
                'verbose_name_plural': 'Inventory Sync Logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['hospital', 'sync_status'], name='resources_i_hospita_3bbdfc_idx'), models.Index(fields=['started_at'], name='resources_i_started_2dd85a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BedOccupancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_type', models.CharField(choices=[('general', 'General Ward'), ('icu', 'ICU'), ('emergency', 'Emergency'), ('pediatric', 'Pediatric'), ('maternity', 'Maternity'), ('surgery', 'Surgery')], max_length=20)),
                ('total_beds', models.PositiveIntegerField()),
                ('occupied_beds', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('reserved_beds', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_occupancy', to='resources.resourcehospital')),
            ],
            options={
                'verbose_name': 'Bed Occupancy',
                'verbose_name_plural': 'Bed Occupancy Records',
                'ordering': ['hospital', 'bed_type'],
                'unique_together': {('hospital', 'bed_type')},
            },
        ),
    ]
