# Generated by Django 4.2.16 on 2026-03-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitals", "0009_hospital_facility_metadata"),
        ("resources", "0004_rename_resources_r_invento_5f09be_idx_resources_r_invento_44bba6_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MLJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "job_type",
                    models.CharField(choices=[("forecast", "Forecast"), ("outbreak", "Outbreak")], max_length=20),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[("facility", "Facility"), ("global", "Global")], default="facility", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("snapshot_ready", "Snapshot Ready"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("callback_received", "Callback Received"),
                            ("completed", "Completed"),
                            ("partial_completed", "Partial Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("model_version", models.CharField(blank=True, max_length=80)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("external_job_id", models.CharField(blank=True, max_length=120)),
                ("callback_request_id", models.CharField(blank=True, max_length=120)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("has_partial_failures", models.BooleanField(default=False)),
                ("partial_failure_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_jobs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ml_jobs",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "ml_job",
            },
        ),
        migrations.CreateModel(
            name="MLOutbreakResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("prediction_horizon_days", models.PositiveIntegerField()),
                ("outbreak_probability", models.DecimalField(decimal_places=4, max_digits=5)),
                ("outbreak_flag", models.BooleanField(default=False)),
                (
                    "risk_level",
                    models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], max_length=10),
                ),
                ("explanation", models.TextField(blank=True)),
                ("decision_log", models.JSONField(blank=True, default=dict)),
                ("neighbors", models.JSONField(blank=True, default=list)),
                ("request_candidates", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_outbreak_results",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outbreak_results", to="ml.mljob"
                    ),
                ),
            ],
            options={
                "db_table": "ml_outbreak_result",
            },
        ),
        migrations.CreateModel(
            name="MLOutbreakNeighborCandidate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=7)),
                ("rank", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "neighbor_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbreak_neighbor_candidates",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "outbreak_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="neighbor_candidates",
                        to="ml.mloutbreakresult",
                    ),
                ),
            ],
            options={
                "db_table": "ml_outbreak_neighbor_candidate",
            },
        ),
        migrations.CreateModel(
            name="MLJobIdempotency",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("endpoint", models.CharField(max_length=120)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("payload_hash", models.CharField(max_length=64)),
                ("response_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ml_job_idempotency",
            },
        ),
        migrations.CreateModel(
            name="MLJobEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=80)),
                ("event_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="ml.mljob"
                    ),
                ),
            ],
            options={
                "db_table": "ml_job_event",
            },
        ),
        migrations.CreateModel(
            name="MLForecastResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("prediction_horizon_days", models.PositiveIntegerField()),
                ("predicted_demand", models.PositiveIntegerField()),
                ("confidence_score", models.DecimalField(decimal_places=4, max_digits=5)),
                ("shareable_quantity", models.IntegerField(default=0)),
                ("restock", models.BooleanField(default=False)),
                ("restock_amount", models.PositiveIntegerField(default=0)),
                ("explanation", models.TextField(blank=True)),
                ("decision_log", models.JSONField(blank=True, default=dict)),
                ("request_candidates", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_forecast_results",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="forecast_results", to="ml.mljob"
                    ),
                ),
                (
                    "resource_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_forecast_results",
                        to="resources.resourcecatalog",
                    ),
                ),
            ],
            options={
                "db_table": "ml_forecast_result",
            },
        ),
        migrations.CreateModel(
            name="MLCallbackDedup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("request_id", models.CharField(max_length=120)),
                ("payload_hash", models.CharField(max_length=64)),
                ("processed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="callback_dedup_records",
                        to="ml.mljob",
                    ),
                ),
            ],
            options={
                "db_table": "ml_callback_dedup",
            },
        ),
        migrations.CreateModel(
            name="FacilityMLSetting",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("max_neighbor_distance_km", models.DecimalField(decimal_places=2, default=20, max_digits=7)),
                ("stock_threshold", models.PositiveIntegerField(default=20)),
                ("outbreak_low_threshold", models.DecimalField(decimal_places=4, default=0.4, max_digits=5)),
                ("outbreak_high_threshold", models.DecimalField(decimal_places=4, default=0.7, max_digits=5)),
                ("notification_cooldown_minutes", models.PositiveIntegerField(default=60)),
                ("max_active_jobs_per_type", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ml_setting", to="hospitals.hospital"
                    ),
                ),
            ],
            options={
                "db_table": "ml_facility_setting",
            },
        ),
        migrations.CreateModel(
            name="MLSchedule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "job_type",
                    models.CharField(choices=[("forecast", "Forecast"), ("outbreak", "Outbreak")], max_length=20),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("daily", "Daily"), ("weekly", "Weekly"), ("cron", "Cron")],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("run_time", models.TimeField(blank=True, null=True)),
                ("cron_expression", models.CharField(blank=True, max_length=120)),
                ("timezone", models.CharField(default="UTC", max_length=60)),
                ("pre_run_offset_minutes", models.PositiveIntegerField(default=0)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_schedules_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_schedules",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "ml_schedule",
                "indexes": [
                    models.Index(fields=["facility", "job_type", "is_active"], name="ml_schedule_facilit_4611c2_idx"),
                    models.Index(fields=["is_active", "next_run_at"], name="ml_schedule_is_acti_ccc13c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MLResultRowError",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("job_type", models.CharField(max_length=20)),
                ("source_row_index", models.PositiveIntegerField(default=0)),
                ("facility_identifier", models.CharField(blank=True, max_length=120)),
                ("resource_identifier", models.CharField(blank=True, max_length=120)),
                ("error_code", models.CharField(max_length=80)),
                ("error_message", models.TextField()),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="row_errors", to="ml.mljob"
                    ),
                ),
            ],
            options={
                "db_table": "ml_result_row_error",
                "indexes": [
                    models.Index(fields=["job", "-created_at"], name="ml_result_r_job_id_1a86b8_idx"),
                    models.Index(fields=["error_code", "-created_at"], name="ml_result_r_error_c_268974_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mloutbreakresult",
            index=models.Index(fields=["facility", "-created_at"], name="ml_outbreak_facilit_093765_idx"),
        ),
        migrations.AddIndex(
            model_name="mloutbreakresult",
            index=models.Index(fields=["job", "-created_at"], name="ml_outbreak_job_id_19d864_idx"),
        ),
        migrations.AddConstraint(
            model_name="mloutbreakresult",
            constraint=models.UniqueConstraint(
                fields=("job", "facility"), name="uniq_ml_outbreak_result_per_job_facility"
            ),
        ),
        migrations.AddIndex(
            model_name="mloutbreakneighborcandidate",
            index=models.Index(fields=["outbreak_result", "rank"], name="ml_outbreak_outbrea_cfdd8d_idx"),
        ),
        migrations.AddConstraint(
            model_name="mloutbreakneighborcandidate",
            constraint=models.UniqueConstraint(
                fields=("outbreak_result", "neighbor_facility"), name="uniq_ml_outbreak_neighbor_per_result"
            ),
        ),
        migrations.AddIndex(
            model_name="mljobidempotency",
            index=models.Index(fields=["endpoint", "-created_at"], name="ml_job_idem_endpoin_54fa95_idx"),
        ),
        migrations.AddConstraint(
            model_name="mljobidempotency",
            constraint=models.UniqueConstraint(
                fields=("actor", "endpoint", "idempotency_key"), name="uniq_ml_job_idempotency"
            ),
        ),
        migrations.AddIndex(
            model_name="mljobevent",
            index=models.Index(fields=["job", "-event_time"], name="ml_job_even_job_id_22f6c1_idx"),
        ),
        migrations.AddIndex(
            model_name="mljobevent",
            index=models.Index(fields=["event_type", "-event_time"], name="ml_job_even_event_t_ab31bb_idx"),
        ),
        migrations.AddIndex(
            model_name="mljob",
            index=models.Index(fields=["job_type", "status", "-created_at"], name="ml_job_job_typ_630823_idx"),
        ),
        migrations.AddIndex(
            model_name="mljob",
            index=models.Index(fields=["facility", "job_type", "-created_at"], name="ml_job_facilit_24981a_idx"),
        ),
        migrations.AddIndex(
            model_name="mljob",
            index=models.Index(fields=["scheduled_time"], name="ml_job_schedul_5c3767_idx"),
        ),
        migrations.AddIndex(
            model_name="mljob",
            index=models.Index(fields=["status", "-updated_at"], name="ml_job_status_fa4b70_idx"),
        ),
        migrations.AddIndex(
            model_name="mlforecastresult",
            index=models.Index(fields=["facility", "-created_at"], name="ml_forecast_facilit_839b65_idx"),
        ),
        migrations.AddIndex(
            model_name="mlforecastresult",
            index=models.Index(fields=["job", "-created_at"], name="ml_forecast_job_id_e370c1_idx"),
        ),
        migrations.AddConstraint(
            model_name="mlforecastresult",
            constraint=models.UniqueConstraint(
                fields=("job", "facility", "resource_catalog"), name="uniq_ml_forecast_result_per_job_row"
            ),
        ),
        migrations.AddIndex(
            model_name="mlcallbackdedup",
            index=models.Index(fields=["processed_at"], name="ml_callback_process_b5105b_idx"),
        ),
        migrations.AddConstraint(
            model_name="mlcallbackdedup",
            constraint=models.UniqueConstraint(fields=("job", "request_id"), name="uniq_ml_callback_dedup_key"),
        ),
    ]
