# Generated by Django 5.2.5 on 2026-04-01 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0010_hospital_inventory_last_sync_source_and_more"),
        ("resources", "0006_resourceinventory_last_verified_at_and_more"),
        ("ml", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLDispenseLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_date", models.DateField(db_index=True)),
                ("quantity_sold", models.PositiveIntegerField()),
                ("source_type", models.CharField(choices=[("api", "API"), ("csv_upload", "CSV Upload"), ("manual", "Manual"), ("derived", "Derived")], default="api", max_length=20)),
                ("source_endpoint", models.CharField(blank=True, max_length=300)),
                ("external_event_id", models.CharField(blank=True, max_length=160)),
                ("payload_hash", models.CharField(max_length=64)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ml_dispense_logs", to="hospitals.hospital")),
                ("resource_catalog", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ml_dispense_logs", to="resources.resourcecatalog")),
            ],
            options={
                "db_table": "ml_dispense_log",
                "indexes": [
                    models.Index(fields=["facility", "event_date"], name="ml_dispense_facilit_5fcc48_idx"),
                    models.Index(fields=["resource_catalog", "event_date"], name="ml_dispense_resourc_640ce6_idx"),
                    models.Index(fields=["source_type", "event_date"], name="ml_dispense_source__20c6fa_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mldispenselog",
            constraint=models.UniqueConstraint(
                condition=~models.Q(external_event_id=""),
                fields=("facility", "external_event_id"),
                name="uniq_ml_dispense_log_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="mldispenselog",
            constraint=models.UniqueConstraint(fields=("facility", "payload_hash"), name="uniq_ml_dispense_log_payload_hash"),
        ),
    ]
