# Generated by Django 4.2.16 on 2026-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0002_mldispenselog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mldispenselog",
            new_name="ml_dispense_facilit_e3414f_idx",
            old_name="ml_dispense_facilit_5fcc48_idx",
        ),
        migrations.RenameIndex(
            model_name="mldispenselog",
            new_name="ml_dispense_resourc_f05eb7_idx",
            old_name="ml_dispense_resourc_640ce6_idx",
        ),
        migrations.RenameIndex(
            model_name="mldispenselog",
            new_name="ml_dispense_source__49336c_idx",
            old_name="ml_dispense_source__20c6fa_idx",
        ),
        migrations.AlterField(
            model_name="mldispenselog",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("api", "API"),
                    ("csv_upload", "CSV Upload"),
                    ("manual", "Manual"),
                    ("internal_sale", "Internal Sale"),
                    ("derived", "Derived"),
                ],
                default="api",
                max_length=20,
            ),
        ),
    ]
