# Generated by Django 4.2.16 on 2026-04-03 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ml", "0003_rename_ml_dispense_facilit_5fcc48_idx_ml_dispense_facilit_e3414f_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLTrainingDatasetSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "model_type",
                    models.CharField(choices=[("model1", "Model 1"), ("model2", "Model 2")], max_length=20),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("schema_version", models.CharField(default="v1", max_length=40)),
                ("snapshot_prefix", models.CharField(blank=True, max_length=255)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_training_datasets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_training_datasets_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ml_training_dataset_snapshot",
            },
        ),
        migrations.CreateModel(
            name="MLTrainingJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "model_type",
                    models.CharField(choices=[("model1", "Model 1"), ("model2", "Model 2")], max_length=20),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("running", "Running"),
                            ("trained", "Trained"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("external_job_id", models.CharField(blank=True, max_length=120)),
                ("model_version_name", models.CharField(blank=True, max_length=120)),
                ("artifact_uri", models.CharField(blank=True, max_length=300)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_training_jobs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_jobs",
                        to="ml.mltrainingdatasetsnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "ml_training_job",
            },
        ),
        migrations.CreateModel(
            name="MLModelVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "model_type",
                    models.CharField(choices=[("model1", "Model 1"), ("model2", "Model 2")], max_length=20),
                ),
                ("version_name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trained", "Trained"),
                            ("stored", "Stored"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="stored",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("artifact_uri", models.CharField(blank=True, max_length=300)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_model_versions_activated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_model_versions_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_model_versions_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_versions",
                        to="ml.mltrainingjob",
                    ),
                ),
            ],
            options={
                "db_table": "ml_model_version",
            },
        ),
        migrations.CreateModel(
            name="MLActiveModelConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "model_type",
                    models.CharField(
                        choices=[("model1", "Model 1"), ("model2", "Model 2")], max_length=20, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_model_configs",
                        to="ml.mlmodelversion",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ml_active_model_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ml_active_model_config",
            },
        ),
        migrations.AddIndex(
            model_name="mltrainingjob",
            index=models.Index(fields=["model_type", "status", "-created_at"], name="ml_training_model_t_756d8a_idx"),
        ),
        migrations.AddIndex(
            model_name="mltrainingdatasetsnapshot",
            index=models.Index(fields=["model_type", "-created_at"], name="ml_training_model_t_104bd8_idx"),
        ),
        migrations.AddIndex(
            model_name="mltrainingdatasetsnapshot",
            index=models.Index(fields=["approval_status", "-created_at"], name="ml_training_approva_60df63_idx"),
        ),
        migrations.AddIndex(
            model_name="mlmodelversion",
            index=models.Index(fields=["model_type", "status", "-created_at"], name="ml_model_ve_model_t_9dacfb_idx"),
        ),
        migrations.AddConstraint(
            model_name="mlmodelversion",
            constraint=models.UniqueConstraint(
                fields=("model_type", "version_name"), name="uniq_ml_model_version_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="mlmodelversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)), fields=("model_type",), name="uniq_ml_model_active_version"
            ),
        ),
    ]
