# Generated by Django 4.2.16 on 2026-04-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml", "0004_mltrainingdatasetsnapshot_mltrainingjob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mljob",
            name="model_version",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
