# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCatalog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("unit_of_measure", models.CharField(blank=True, max_length=50)),
                ("is_shareable", models.BooleanField(default=True)),
                ("minimum_stock_level", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_items",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "resources_resourcecatalog",
            },
        ),
        migrations.CreateModel(
            name="ResourceInventory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                ("quantity_reserved", models.PositiveIntegerField(default=0)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("last_restocked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="resources.resourcecatalog",
                    ),
                ),
            ],
            options={
                "db_table": "resources_resourceinventory",
            },
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("unit_of_measure", models.CharField(blank=True, help_text="e.g. 'units', 'ml', 'kg'", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "resources_resourcetype",
            },
        ),
        migrations.CreateModel(
            name="ResourceShare",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity_offered", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused"), ("closed", "Closed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="resources.resourcecatalog",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_shares_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_shares",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "resources_resourceshare",
            },
        ),
        migrations.AddField(
            model_name="resourcecatalog",
            name="resource_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="catalog_items", to="resources.resourcetype"
            ),
        ),
        migrations.CreateModel(
            name="ResourceTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("restock", "Restock"),
                            ("adjustment", "Adjustment"),
                            ("transfer_out", "Transfer Out"),
                            ("transfer_in", "Transfer In"),
                            ("reserved", "Reserved"),
                            ("released", "Released"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_delta", models.IntegerField(help_text="Positive=increase, negative=decrease")),
                ("balance_after", models.PositiveIntegerField()),
                ("reference_id", models.UUIDField(blank=True, help_text="e.g. ResourceRequest.id", null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="resources.resourceinventory",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resource_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resources_resourcetransaction",
                "indexes": [models.Index(fields=["inventory", "-created_at"], name="resources_r_invento_8b8afc_idx")],
            },
        ),
        migrations.AlterUniqueTogether(
            name="resourcecatalog",
            unique_together={("hospital", "name", "resource_type")},
        ),
    ]
