# Generated by Django 4.2.16 on 2026-03-15 15:10

from decimal import Decimal
from django.db import migrations, models


def copy_reserved_quantity(apps, schema_editor):
    ResourceInventory = apps.get_model("resources", "ResourceInventory")
    for inventory in ResourceInventory.objects.all().iterator():
        inventory.reserved_quantity = inventory.quantity_reserved
        inventory.save(update_fields=["reserved_quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceinventory",
            name="currency",
            field=models.CharField(default="BDT", max_length=10),
        ),
        migrations.AddField(
            model_name="resourceinventory",
            name="price_per_unit",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="resourceinventory",
            name="reserved_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(copy_reserved_quantity, migrations.RunPython.noop),
    ]
