# Generated by Django 4.2.16 on 2026-03-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_resourceinventorybatch"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="resourceinventorybatch",
            new_name="resources_r_invento_44bba6_idx",
            old_name="resources_r_invento_5f09be_idx",
        ),
        migrations.RenameIndex(
            model_name="resourceinventorybatch",
            new_name="resources_r_invento_86d522_idx",
            old_name="resources_r_invento_b81abf_idx",
        ),
    ]
