# Generated by Django 4.2.16 on 2026-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_rename_resources_r_invento_5f09be_idx_resources_r_invento_44bba6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceinventorybatch",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
