# Generated by Django 4.2.16 on 2026-03-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_resourceinventorybatch_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceinventory",
            name="last_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourceinventory",
            name="verification_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="resourceinventory",
            name="verification_status",
            field=models.CharField(
                choices=[("verified", "Verified"), ("pending_sync", "Pending Sync"), ("stale", "Stale")],
                db_index=True,
                default="verified",
                max_length=20,
            ),
        ),
    ]
