# Generated by Django 4.2.16 on 2026-04-07 09:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0006_resourceinventory_last_verified_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                (
                    "discount_type",
                    models.CharField(choices=[("percentage", "Percentage"), ("fixed", "Fixed")], max_length=20),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applies_to_scope",
                    models.CharField(
                        choices=[
                            ("inventory", "Inventory"),
                            ("batch", "Batch"),
                            ("sale", "Sale"),
                            ("share_request", "Share Request"),
                        ],
                        default="inventory",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resources_discountpolicy",
            },
        ),
        migrations.AddField(
            model_name="resourceinventory",
            name="active_discount_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_inventories",
                to="resources.discountpolicy",
            ),
        ),
        migrations.AddIndex(
            model_name="discountpolicy",
            index=models.Index(fields=["applies_to_scope", "is_active"], name="resources_d_applies_1e94cf_idx"),
        ),
        migrations.AddIndex(
            model_name="discountpolicy",
            index=models.Index(fields=["start_at", "end_at"], name="resources_d_start_a_1e049c_idx"),
        ),
        migrations.AddConstraint(
            model_name="discountpolicy",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_at__isnull", True),
                    ("start_at__isnull", True),
                    ("end_at__gte", models.F("start_at")),
                    _connector="OR",
                ),
                name="discount_policy_start_before_end",
            ),
        ),
    ]
