# Generated by Django 4.2.16 on 2026-03-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("carrier_name", models.CharField(blank=True, max_length=200)),
                ("tracking_number", models.CharField(blank=True, max_length=200)),
                ("estimated_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("actual_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_shipments",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "origin_hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_shipments",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "shipments_shipment",
            },
        ),
        migrations.CreateModel(
            name="ShipmentTracking",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipment_tracking_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "shipments_tracking",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status", "-created_at"], name="shipments_s_status_c4d56f_idx"),
        ),
    ]
