# Generated by Django 4.2.16 on 2026-03-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="reference",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
