# Generated by Django 4.2.16 on 2026-03-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_shipment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="cancel_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="dispatch_token",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="shipment",
            name="dispatch_token_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="receive_token",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="shipment",
            name="receive_token_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="return_token",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="shipment",
            name="return_token_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="rider_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="shipment",
            name="rider_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="shipment",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="vehicle_info",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_dispatch", "Pending Dispatch"),
                    ("dispatched", "Dispatched"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancel_requested", "Cancel Requested"),
                    ("returning", "Returning"),
                    ("returned", "Returned"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending_dispatch",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipmenttracking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_dispatch", "Pending Dispatch"),
                    ("dispatched", "Dispatched"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancel_requested", "Cancel Requested"),
                    ("returning", "Returning"),
                    ("returned", "Returned"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
    ]
