# Generated by Django 4.2.16 on 2026-04-02 17:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0006_resourceinventory_last_verified_at_and_more"),
        ("hospitals", "0012_hospital_advanced_integration_eligible_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalSale",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_date", models.DateField(db_index=True)),
                ("quantity_sold", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("total_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14)),
                ("currency", models.CharField(default="BDT", max_length=10)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk In"),
                            ("prescription", "Prescription"),
                            ("online", "Online"),
                            ("other", "Other"),
                        ],
                        default="walk_in",
                        max_length=20,
                    ),
                ),
                ("client_reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_sales",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "resource_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_sales",
                        to="resources.resourcecatalog",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internal_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_internal_sale",
                "indexes": [
                    models.Index(fields=["facility", "event_date"], name="sales_inter_facilit_b272de_idx"),
                    models.Index(fields=["resource_catalog", "event_date"], name="sales_inter_resourc_826d5d_idx"),
                    models.Index(fields=["channel", "-created_at"], name="sales_inter_channel_7691c2_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="internalsale",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_reference", ""), _negated=True),
                fields=("facility", "client_reference"),
                name="uniq_internal_sale_client_reference",
            ),
        ),
    ]
