# Generated by Django 4.2.16 on 2026-04-07 09:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_discountpolicy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailSale",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_selling_price_snapshot", models.DecimalField(decimal_places=2, max_digits=12)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("final_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("sold_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("customer_reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retail_sales",
                        to="resources.resourceinventorybatch",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retail_sales",
                        to="resources.resourceinventory",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retail_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_retail_sale",
                "indexes": [
                    models.Index(fields=["inventory", "-sold_at"], name="sales_retai_invento_bb949b_idx"),
                    models.Index(fields=["sold_by", "-sold_at"], name="sales_retai_sold_by_413560_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="retailsale",
            constraint=models.CheckConstraint(
                check=models.Q(("quantity__gt", 0)), name="retail_sale_quantity_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="retailsale",
            constraint=models.CheckConstraint(
                check=models.Q(("discount_amount__gte", Decimal("0.00"))), name="retail_sale_discount_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="retailsale",
            constraint=models.CheckConstraint(
                check=models.Q(("final_total__gte", Decimal("0.00"))), name="retail_sale_final_total_non_negative"
            ),
        ),
    ]
