# Generated by Django 4.2.16 on 2026-03-29 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospitals", "0010_hospital_inventory_last_sync_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryImportJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_type", models.CharField(choices=[("CSV", "CSV")], default="CSV", max_length=20)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("MERGE", "Merge"),
                            ("REPLACE_UPLOADED_SCOPE", "Replace Uploaded Scope"),
                            ("FULL_REPLACE", "Full Replace"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("idempotency_key", models.CharField(blank=True, max_length=128)),
                ("confirm_full_replace", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALIDATED", "Validated"),
                            ("APPLYING", "Applying"),
                            ("APPLIED", "Applied"),
                            ("PARTIALLY_APPLIED", "Partially Applied"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("applied_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_import_jobs",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_import_jobs_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "inventory_module_import_job",
            },
        ),
        migrations.CreateModel(
            name="InventoryImportError",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("row_number", models.PositiveIntegerField()),
                ("field_name", models.CharField(blank=True, max_length=80)),
                ("error_code", models.CharField(max_length=80)),
                ("error_message", models.TextField()),
                ("raw_row", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="inventory_module.inventoryimportjob",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_module_import_error",
            },
        ),
        migrations.AddIndex(
            model_name="inventoryimportjob",
            index=models.Index(fields=["facility", "-created_at"], name="inventory_m_facilit_548614_idx"),
        ),
        migrations.AddIndex(
            model_name="inventoryimportjob",
            index=models.Index(fields=["status", "-updated_at"], name="inventory_m_status_baac9b_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventoryimportjob",
            constraint=models.UniqueConstraint(
                fields=("facility", "file_hash"), name="uniq_inventory_import_job_facility_file_hash"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryimporterror",
            index=models.Index(fields=["import_job", "row_number"], name="inventory_m_import__baf0ae_idx"),
        ),
    ]
