# Generated by Django 4.2.16 on 2026-04-01 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0010_hospital_inventory_last_sync_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory_module", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCSVValidationContext",
            fields=[
                ("file_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                ("language", models.CharField(default="en", max_length=10)),
                ("expected_schema", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("sample_rows", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_csv_validation_contexts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_csv_validation_contexts",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_module_validation_context",
                "indexes": [
                    models.Index(fields=["facility", "-created_at"], name="inventory_m_facilit_7db6c4_idx"),
                    models.Index(fields=["file_hash"], name="inventory_m_file_ha_6967e1_idx"),
                ],
            },
        ),
    ]
