# Generated by Django 4.2.16 on 2026-04-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("hospitals", "0011_hospitalregistrationrequest_api_check_results_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory_module", "0002_inventorycsvvalidationcontext"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCSVChatSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CLOSED", "Closed")],
                        db_index=True,
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_csv_chat_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_csv_chat_sessions",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "validation_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to="inventory_module.inventorycsvvalidationcontext",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_module_chat_session",
            },
        ),
        migrations.CreateModel(
            name="InventoryCSVChatMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("USER", "User"), ("ASSISTANT", "Assistant"), ("SYSTEM", "System")], max_length=20
                    ),
                ),
                ("content", models.TextField()),
                ("out_of_scope", models.BooleanField(default=False)),
                ("message_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="inventory_module.inventorycsvchatsession",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_module_chat_message",
            },
        ),
        migrations.AddIndex(
            model_name="inventorycsvchatsession",
            index=models.Index(fields=["facility", "-created_at"], name="inventory_m_facilit_1d705d_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorycsvchatsession",
            index=models.Index(fields=["validation_context", "-created_at"], name="inventory_m_validat_6cf591_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorycsvchatsession",
            index=models.Index(fields=["status", "-updated_at"], name="inventory_m_status_b544c4_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorycsvchatmessage",
            index=models.Index(fields=["session", "created_at"], name="inventory_m_session_c9a4f6_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorycsvchatmessage",
            index=models.Index(fields=["role", "-created_at"], name="inventory_m_role_3e498c_idx"),
        ),
    ]
